/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VentanaPrestamos.java
 *
 * Created on 11/05/2010, 03:05:40 PM
 */

package co.edu.eam.biblioteca.vista;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import co.edu.eam.biblioteca.persistencia.modelo.entidades.Libro;
import co.edu.eam.biblioteca.persistencia.modelo.entidades.Prestamo;
import co.edu.eam.biblioteca.persistencia.modelo.entidades.Usuario;
import co.edu.eam.bibliteca.excepciones.ExcepcionNegocio;
import co.ema.edu.biblioteca.controlador.ControladorVentanaPrestamo;

/**
* This code was edited or generated using CloudGarden's Jigloo
* SWT/Swing GUI Builder, which is free for non-commercial
* use. If Jigloo is being used commercially (ie, by a corporation,
* company or business for any purpose whatever) then you
* should purchase a license for each developer using Jigloo.
* Please visit www.cloudgarden.com for details.
* Use of Jigloo implies acceptance of these licensing terms.
* A COMMERCIAL LICENSE HAS NOT BEEN PURCHASED FOR
* THIS MACHINE, SO JIGLOO OR THIS CODE CANNOT BE USED
* LEGALLY FOR ANY CORPORATE OR COMMERCIAL PURPOSE.
*/
/**
 *
 * @author Camilo Andres
 */
public class VentanaPrestamos extends javax.swing.JInternalFrame {

	Usuario usuarioAct;
	private ControladorVentanaPrestamo controlador;

	/** Creates new form VentanaPrestamos */
	public VentanaPrestamos() {
		initComponents();
		controlador = new ControladorVentanaPrestamo();
		usuarioAct = null;
		setVisible(true);
		setResizable(false);
		setClosable(true);
		setMaximizable(false);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		tfCedulaUsuario = new javax.swing.JTextField();
		bBuscarUsuario = new javax.swing.JButton();
		jLabel2 = new javax.swing.JLabel();
		tfNombreUsuario = new javax.swing.JTextField();
		tfNumeroRetrasos = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		jPanel2 = new javax.swing.JPanel();
		jLabel4 = new javax.swing.JLabel();
		tfCodigoLibro = new javax.swing.JTextField();
		jLabel5 = new javax.swing.JLabel();
		tfNombreLibro = new javax.swing.JTextField();
		bAgregarPrestamo = new javax.swing.JButton();
		jPanel3 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		tablaPRestamos = new javax.swing.JTable();
		bEntregarPrestamo = new javax.swing.JButton();

		setIconifiable(true);
		setTitle("Prestar/Entregar Libro");
		setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Public_32x32-32 (2).png"))); // NOI18N

		jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Usuario"));

		jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		jLabel1.setText("Cedula");

		bBuscarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Find.png"))); // NOI18N
		bBuscarUsuario.setText("Buscar");
		bBuscarUsuario.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				bBuscarUsuarioActionPerformed(evt);
			}
		});

		jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		jLabel2.setText("Nombre");

		tfNombreUsuario.setEditable(false);

		tfNumeroRetrasos.setEditable(false);

		jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		jLabel3.setText("Numero Retrasos");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap()
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addGroup(jPanel1Layout.createSequentialGroup().addComponent(jLabel2)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(tfNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 155,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jLabel3)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(tfNumeroRetrasos))
								.addGroup(jPanel1Layout.createSequentialGroup().addComponent(jLabel1)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(tfCedulaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 180,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(bBuscarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 130,
												javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addGap(31, 31, 31)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap()
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel1)
								.addComponent(tfCedulaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(bBuscarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 22,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel2)
								.addComponent(tfNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel3).addComponent(tfNumeroRetrasos,
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Libro"));

		jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		jLabel4.setText("Codigo");

		jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		jLabel5.setText("Nombre");

		bAgregarPrestamo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Add_32x32-32.png"))); // NOI18N
		bAgregarPrestamo.setText("Agregar");
		bAgregarPrestamo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		bAgregarPrestamo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
		bAgregarPrestamo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		bAgregarPrestamo.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				bAgregarPrestamoActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup().addContainerGap()
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jLabel4).addComponent(jLabel5))
						.addGap(37, 37, 37)
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
								.addComponent(tfNombreLibro).addComponent(tfCodigoLibro,
										javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE))
						.addGap(18, 18, 18).addComponent(bAgregarPrestamo)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup().addGroup(jPanel2Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel2Layout.createSequentialGroup()
								.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel4).addComponent(tfCodigoLibro,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(18, 18, 18)
								.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(tfNombreLibro, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabel5)))
						.addComponent(bAgregarPrestamo)).addContainerGap(19, Short.MAX_VALUE)));

		jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Prestamos"));

		tablaPRestamos
				.setModel(new javax.swing.table.DefaultTableModel(
						new Object[][] { { null, null, null, null }, { null, null, null, null },
								{ null, null, null, null }, { null, null, null, null } },
						new String[] { "Codigo", "Nombre", "Fecha", "Vencido" }) {
					boolean[] canEdit = new boolean[] { false, false, true, false };

					public boolean isCellEditable(int rowIndex, int columnIndex) {
						return canEdit[columnIndex];
					}
				});
		jScrollPane1.setViewportView(tablaPRestamos);

		bEntregarPrestamo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Delete_32x32-32.png"))); // NOI18N
		bEntregarPrestamo.setText("Quitar");
		bEntregarPrestamo.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				bEntregarPrestamoActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout.setHorizontalGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel3Layout.createSequentialGroup().addContainerGap()
						.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(bEntregarPrestamo))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		jPanel3Layout.setVerticalGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel3Layout.createSequentialGroup()
						.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(bEntregarPrestamo).addContainerGap(18, Short.MAX_VALUE)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)
								.addGroup(javax.swing.GroupLayout.Alignment.LEADING,
										layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
												.addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
						.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addContainerGap()));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void bBuscarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_bBuscarUsuarioActionPerformed
		try {
			String ced = tfCedulaUsuario.getText();
			Usuario u = controlador.buscarUsuario(ced);
			usuarioAct = u;
			if (u != null) {
				tfNombreUsuario.setText(u.getNombre());
				llenarTabla();
			} else {
				JOptionPane.showMessageDialog(null, "no se encontro al usuario");
			}

		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

	}// GEN-LAST:event_bBuscarUsuarioActionPerformed

	private void bAgregarPrestamoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_bAgregarPrestamoActionPerformed
		try {

			
			String ced = tfCedulaUsuario.getText();
			Usuario us = controlador.buscarUsuario(ced);
			String codLib = tfCodigoLibro.getText();
			Libro lib = controlador.buscarLibro(codLib);
			Prestamo pre = new Prestamo(lib, us);
			controlador.agregarPrestamo(pre, codLib);

		} catch (ExcepcionNegocio ex) {
			ex.getMessage();
			ex.printStackTrace();

		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

	}// GEN-LAST:event_bAgregarPrestamoActionPerformed

	private void bEntregarPrestamoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_bEntregarPrestamoActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_bEntregarPrestamoActionPerformed

	/**
	 * lista la tabla
	 * 
	 * @throws Exception
	 *             en caso de una excepcion tecnica
	 */
	public void llenarTabla() {
		try {
			DefaultTableModel dtm = (DefaultTableModel) tablaPRestamos.getModel();
			dtm.setRowCount(0);

			java.util.List<Prestamo> lista;
			lista = controlador.prestamosUsuario(usuarioAct);
			for (Prestamo prestamo : lista) {
				dtm.addRow(new Object[] { prestamo.getLibro().getCodigo(), prestamo.getLibro().getNombre() });
			}
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton bAgregarPrestamo;
	private javax.swing.JButton bBuscarUsuario;
	private javax.swing.JButton bEntregarPrestamo;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable tablaPRestamos;
	private javax.swing.JTextField tfCedulaUsuario;
	private javax.swing.JTextField tfCodigoLibro;
	private javax.swing.JTextField tfNombreLibro;
	private javax.swing.JTextField tfNombreUsuario;
	private javax.swing.JTextField tfNumeroRetrasos;
	// End of variables declaration//GEN-END:variables

}
