/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VentanaCrearVuelo.java
 *
 * Created on 08-oct-2012, 3:15:11
 */
package co.edu.eam.ingesoft.desarrollo.aerolinea.gui.visa;

import java.util.Date;

import javax.swing.JOptionPane;

import co.edu.eam.ingesoft.desarrollo.aerolinea.definiciones.IDAOCiudad;
import co.edu.eam.ingesoft.desarrollo.aerolinea.definiciones.IDAOViaje;
import co.edu.eam.ingesoft.desarrollo.aerolinea.definiciones.IDAOViajero;
import co.edu.eam.ingesoft.desarrollo.aerolinea.definicionesJDBC.DAOViajero;
import co.edu.eam.ingesoft.desarrollo.aerolinea.persistencia.implementacionsJPA.DAOCiudad;
import co.edu.eam.ingesoft.desarrollo.aerolinea.persistencia.implementacionsJPA.DAOViaje;
import co.edu.eam.ingesoft.desarrollo.aerolinea.persistencia.modelo.Ciudad;
import co.edu.eam.ingesoft.desarrollo.aerolinea.persistencia.modelo.Viaje;
import co.edu.eam.ingesoft.desarrollo.aerolinea.persistencia.modelo.Viajero;

/**
 *
 * @author Camilo Andres
 */
public class VentanaCrearVuelo extends javax.swing.JFrame {

	private IDAOCiudad daoCiudad;
	private IDAOViajero daoViajero;
	private IDAOViaje daoViaje;
    /** Creates new form VentanaCrearVuelo */
    public VentanaCrearVuelo() {
        initComponents();
        daoCiudad = new DAOCiudad();
        daoViajero = new DAOViajero();
        daoViaje = new DAOViaje();
        refrescarComboCiudades();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        tfCedula = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tfNombre = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tfApellido = new javax.swing.JTextField();
        btnCrearViajero = new javax.swing.JButton();
        btnBorrarViajero = new javax.swing.JButton();
        btnBuscarViajero = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        tfCodigoVuelo = new javax.swing.JTextField();
        cbOrigen = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cbDestino = new javax.swing.JComboBox();
        btnBuscarVuelo = new javax.swing.JButton();
        btnCrearVuelo = new javax.swing.JButton();
        btnEditarVuelo = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        dcFEchaVuelo = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel9.setText("Cedula:");

        jLabel10.setText("Nombre:");

        jLabel11.setText("Apellido:");

        btnCrearViajero.setText("Crear");
        btnCrearViajero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearViajeroActionPerformed(evt);
            }
        });

        btnBorrarViajero.setText("Borrar");
        btnBorrarViajero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarViajeroActionPerformed(evt);
            }
        });

        btnBuscarViajero.setText("Buscar");
        btnBuscarViajero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarViajeroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnCrearViajero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBuscarViajero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBorrarViajero))
                    .addComponent(tfCedula)
                    .addComponent(tfNombre)
                    .addComponent(tfApellido))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tfCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tfApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrearViajero)
                    .addComponent(btnBorrarViajero)
                    .addComponent(btnBuscarViajero))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Crud Viajero", jPanel2);

        jLabel5.setText("Codigo");

        jLabel6.setText("Origen");

        jLabel7.setText("Destino");

        btnBuscarVuelo.setText("Buscar");
        btnBuscarVuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarVueloActionPerformed(evt);
            }
        });

        btnCrearVuelo.setText("Crear");
        btnCrearVuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearVueloActionPerformed(evt);
            }
        });

        btnEditarVuelo.setText("Editar");
        btnEditarVuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarVueloActionPerformed(evt);
            }
        });

        jLabel8.setText("Fecha");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnCrearVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEditarVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(tfCodigoVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(btnBuscarVuelo))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cbDestino, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbOrigen, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(dcFEchaVuelo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(262, 262, 262))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfCodigoVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscarVuelo)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dcFEchaVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrearVuelo)
                    .addComponent(btnEditarVuelo))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("CRUD Viaje", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearViajeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearViajeroActionPerformed
    	try {
    		if(tfCedula.getText().isEmpty() ){
    	        JOptionPane.showMessageDialog(null, "ingrese una cedula");

    		}else{
    	String cedula = tfCedula.getText();
		String nombre = tfNombre.getText();
		String ape = tfApellido.getText();
    	
		Viajero viajero = new Viajero(cedula, ape, nombre);
     	daoViajero.crear(viajero);
        JOptionPane.showMessageDialog(null, "se ha creado el viajero en la base de datos");
    	}
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    	
    }//GEN-LAST:event_btnCrearViajeroActionPerformed

    private void btnBuscarViajeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarViajeroActionPerformed
    	try {
    	String cedula = tfCedula.getText();
		Viajero viaj = daoViajero.buscar(cedula);
		
		if(viaj != null){
			
			tfCedula.setText(viaj.getCedula());
			tfNombre.setText(viaj.getNombre());
			tfApellido.setText(viaj.getApelido());
		}else{
			JOptionPane.showMessageDialog(null, "El viajero no se encuentra registrado");

		}
		
		
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    	
    	
    	
    	
    	
    	
    }//GEN-LAST:event_btnBuscarViajeroActionPerformed

    private void btnBorrarViajeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarViajeroActionPerformed
    	try {
    	if(tfCedula.getText().isEmpty()){
    		JOptionPane.showMessageDialog(null, "debe buscar un viajero");

    	}else{
    	String cedula = tfCedula.getText();
		String nombre = tfNombre.getText();
		String ape = tfApellido.getText();
		Viajero viajero = new Viajero(cedula, ape, nombre);
		
		daoViajero.eliminar(viajero);
		JOptionPane.showMessageDialog(null, "se ha eliminado");
    	}
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
    	
    	
    }//GEN-LAST:event_btnBorrarViajeroActionPerformed

    private void btnCrearVueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearVueloActionPerformed
    	 try {
    	int codVuelo = Integer.parseInt(tfCodigoVuelo.getText());
    	Ciudad origen = (Ciudad) cbOrigen.getSelectedItem();
    	Ciudad ciudOrig = new Ciudad(origen.getCodigoCiud(),origen.getNombreCiudad());
    	Ciudad destino = (Ciudad) cbDestino.getSelectedItem();
    	Ciudad ciudDes = new Ciudad(destino.getCodigoCiud(),destino.getNombreCiudad());
        Date fecha = dcFEchaVuelo.getDate();
        Viaje viaje = new Viaje(codVuelo, fecha, ciudDes, ciudOrig);   
		daoViaje.crear(viaje);
		JOptionPane.showMessageDialog(null, "se ha creado el viaje");

		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    	
    	
    }//GEN-LAST:event_btnCrearVueloActionPerformed

    private void btnEditarVueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarVueloActionPerformed
    	try {
    		
    	if(tfCodigoVuelo.getText().isEmpty()){
    		JOptionPane.showMessageDialog(null, "Debe buscar un viaje");
    	}else{
    	int codVuelo = Integer.parseInt(tfCodigoVuelo.getText());
    	Ciudad origen = (Ciudad) cbOrigen.getSelectedItem();
    	Ciudad ciudOrig = new Ciudad(origen.getCodigoCiud(),origen.getNombreCiudad());
    	Ciudad destino = (Ciudad) cbDestino.getSelectedItem();
    	Ciudad ciudDes = new Ciudad(destino.getCodigoCiud(),destino.getNombreCiudad());
        Date fecha = dcFEchaVuelo.getDate();
        Viaje viaje = new Viaje(codVuelo, fecha, ciudDes, ciudOrig);   
	
		daoViaje.editar(viaje);
		JOptionPane.showMessageDialog(null, "se ha editado el viaje");
    	}
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    	
    	
    	
    }//GEN-LAST:event_btnEditarVueloActionPerformed

    private void btnBuscarVueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarVueloActionPerformed
    	try {
    	    if(tfCodigoVuelo.getText().isEmpty()){
    		JOptionPane.showMessageDialog(null, "debe buscar un viaje");

    	    }
    		int cod = Integer.parseInt(tfCodigoVuelo.getText());
    		Viaje v = daoViaje.buscar(cod);
    	
    		if(v != null){
    			tfCodigoVuelo.setText(v.getCodigoViaje()+"");
    			cbOrigen.setSelectedItem(v.getCiudadOrigen());
    			cbDestino.setSelectedItem(v.getCiudadDestino());
    			dcFEchaVuelo.setDate(v.getFecha());
    			
    		}else{
				JOptionPane.showMessageDialog(null, "El viaje no se encuentra registrado");

    		}
    	
    	
    	
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    	
    	
    	
    }//GEN-LAST:event_btnBuscarVueloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new VentanaCrearVuelo().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrarViajero;
    private javax.swing.JButton btnBuscarViajero;
    private javax.swing.JButton btnBuscarVuelo;
    private javax.swing.JButton btnCrearViajero;
    private javax.swing.JButton btnCrearVuelo;
    private javax.swing.JButton btnEditarVuelo;
    private javax.swing.JComboBox cbDestino;
    private javax.swing.JComboBox cbOrigen;
    private com.toedter.calendar.JDateChooser dcFEchaVuelo;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField tfApellido;
    private javax.swing.JTextField tfCedula;
    private javax.swing.JTextField tfCodigoVuelo;
    private javax.swing.JTextField tfNombre;
    // End of variables declaration//GEN-END:variables
    
    
    
    public void refrescarComboCiudades() {
    	try {
    		java.util.List<Ciudad> listaCiudades = daoCiudad.ListarCiudad();
    		cbDestino.removeAllItems();
    		cbOrigen.removeAllItems();
    		cbDestino.addItem("Seleccione una opción");
    		cbOrigen.addItem("Seleccione una opción");
    		for(int i=0; i<listaCiudades.size(); i++){
    			cbDestino.addItem(listaCiudades.get(i));
    			cbOrigen.addItem(listaCiudades.get(i));

    		}	
    	} catch (Exception e) {
    		// TODO Auto-generated catch block
    		e.printStackTrace();
    	}
    }
}






