/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VentanaCrearCancelarCuenta.java
 *
 * Created on 13/08/2010, 03:36:40 PM
 */
package co.edu.eam.diseno.banco.vista.gui;

import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import co.edu.eam.diseno.banco.vista.controladores.ControladorCrearCancelarCuenta;
import co.edu.eam.ingesoft.desarrollo.banco.persistencia.modelo.entidades.Cliente;
import co.edu.eam.ingesoft.desarrollo.banco.persistencia.modelo.entidades.Cuenta;
import co.edu.eam.ingesoft.desarrollo.banco.persistencia.modelo.entidades.TipoCuenta;
import co.edu.eam.ingesoft.desarrollo.logica.excepciones.ExcepcionNegocio;

/**
 *
 * @author Camilo Andres
 */
public class VentanaCrearCancelarCuenta extends javax.swing.JInternalFrame {

	private ControladorCrearCancelarCuenta controlador;
	private Cliente clienteBuscado;

	/** Creates new form VentanaCrearCancelarCuenta */
	public VentanaCrearCancelarCuenta() {

		controlador = new ControladorCrearCancelarCuenta();
		initComponents();

		buttonGroup1.add(jRadioButtonAHORRO);
		buttonGroup1.add(jRadioButtonCORRIENTE);
		buttonGroup1.add(jRadioButtonEMPRESARIAL);

		setMaximizable(false);
		setResizable(false);
		setIconifiable(true);
		setVisible(true);
		setClosable(true);

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		buttonGroup1 = new javax.swing.ButtonGroup();
		buttonGroup2 = new javax.swing.ButtonGroup();
		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		tfCEdulaCLiente = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();
		tfNombreCliente = new javax.swing.JTextField();
		BBuscarCLiente = new javax.swing.JButton();
		jLabel6 = new javax.swing.JLabel();
		jTextFieldTOTALDINERO = new javax.swing.JTextField();
		jScrollPane1 = new javax.swing.JScrollPane();
		tablaCuentasClientes = new javax.swing.JTable();
		jPanel2 = new javax.swing.JPanel();
		jLabel3 = new javax.swing.JLabel();
		tfNumeroCuenta = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		tfPasswordCuenta = new javax.swing.JPasswordField();
		jRadioButtonAHORRO = new javax.swing.JRadioButton();
		jRadioButtonCORRIENTE = new javax.swing.JRadioButton();
		jRadioButtonEMPRESARIAL = new javax.swing.JRadioButton();
		BCrearCuenta = new javax.swing.JButton();
		jLabel5 = new javax.swing.JLabel();

		setTitle("Crear/Cancelar Cuenta");
		setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/001_shoppingcart_full.png"))); // NOI18N

		jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cliente",
				javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION,
				new java.awt.Font("Tahoma", 1, 12))); // NOI18N

		jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12));
		jLabel1.setText("Cedula");

		jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12));
		jLabel2.setText("Nombre");

		tfNombreCliente.setEditable(false);

		BBuscarCLiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Search.png"))); // NOI18N
		BBuscarCLiente.setText("Buscar");
		BBuscarCLiente.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				BBuscarCLienteActionPerformed(evt);
			}
		});

		jLabel6.setText("TOTAL DINERO");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(
						jPanel1Layout
								.createParallelGroup(
										javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap().addGroup(jPanel1Layout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
												jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE,
																107, Short.MAX_VALUE)
														.addComponent(jLabel2))
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addGroup(jPanel1Layout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.TRAILING)
																.addComponent(tfCEdulaCLiente,
																		javax.swing.GroupLayout.DEFAULT_SIZE, 249,
																		Short.MAX_VALUE)
																.addComponent(tfNombreCliente,
																		javax.swing.GroupLayout.DEFAULT_SIZE, 249,
																		Short.MAX_VALUE)
																.addComponent(jTextFieldTOTALDINERO,
																		javax.swing.GroupLayout.Alignment.LEADING,
																		javax.swing.GroupLayout.DEFAULT_SIZE, 249,
																		Short.MAX_VALUE))
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addComponent(BBuscarCLiente))
										.addComponent(jLabel6)).addContainerGap()));
		jPanel1Layout
				.setVerticalGroup(
						jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel1Layout
										.createSequentialGroup().addContainerGap().addGroup(jPanel1Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
												.addComponent(BBuscarCLiente, javax.swing.GroupLayout.Alignment.LEADING,
														javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
												.addGroup(
														javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout
																.createSequentialGroup().addGroup(jPanel1Layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																		.addComponent(tfCEdulaCLiente,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(jLabel1))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(jPanel1Layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																		.addComponent(tfNombreCliente,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(jLabel2))))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(jPanel1Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jLabel6).addComponent(jTextFieldTOTALDINERO,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))));

		tablaCuentasClientes.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, null }, { null, null }, { null, null }, { null, null } },
				new String[] { "Numero", "Saldo" }) {
			boolean[] canEdit = new boolean[] { false, false };

			public boolean isCellEditable(int rowIndex, int columnIndex) {
				return canEdit[columnIndex];
			}
		});
		tablaCuentasClientes.setRowHeight(40);
		jScrollPane1.setViewportView(tablaCuentasClientes);
		tablaCuentasClientes.getColumnModel().getColumn(0).setResizable(false);
		tablaCuentasClientes.getColumnModel().getColumn(1).setResizable(false);

		jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cuenta",
				javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION,
				new java.awt.Font("Tahoma", 1, 12))); // NOI18N

		jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12));
		jLabel3.setText("Numero");

		jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12));
		jLabel4.setText("Password");

		buttonGroup1.add(jRadioButtonAHORRO);
		jRadioButtonAHORRO.setText("AHORRO");

		buttonGroup1.add(jRadioButtonCORRIENTE);
		jRadioButtonCORRIENTE.setText("CORRIENTE");

		buttonGroup1.add(jRadioButtonEMPRESARIAL);
		jRadioButtonEMPRESARIAL.setText("EMPRESARIAL");

		BCrearCuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Add.png"))); // NOI18N
		BCrearCuenta.setText("Crear");
		BCrearCuenta.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				BCrearCuentaActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup().addContainerGap()
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jLabel3).addComponent(jLabel4))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel2Layout.createSequentialGroup().addComponent(jRadioButtonAHORRO)
										.addGap(18, 18, 18).addComponent(jRadioButtonCORRIENTE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(jRadioButtonEMPRESARIAL).addContainerGap())
								.addGroup(jPanel2Layout.createSequentialGroup()
										.addGroup(jPanel2Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(tfPasswordCuenta, javax.swing.GroupLayout.DEFAULT_SIZE,
														284, Short.MAX_VALUE)
												.addComponent(tfNumeroCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, 284,
														Short.MAX_VALUE))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(BCrearCuenta, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addGap(29, 29, 29)))));
		jPanel2Layout
				.setVerticalGroup(
						jPanel2Layout
								.createParallelGroup(
										javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(
										jPanel2Layout.createSequentialGroup().addGroup(jPanel2Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
												.addComponent(BCrearCuenta, javax.swing.GroupLayout.Alignment.LEADING,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addGroup(javax.swing.GroupLayout.Alignment.LEADING,
														jPanel2Layout.createSequentialGroup()
																.addGroup(jPanel2Layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																		.addComponent(tfNumeroCuenta,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(jLabel3))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(jPanel2Layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																		.addComponent(tfPasswordCuenta,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(jLabel4))))
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
												.addGroup(
														jPanel2Layout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.BASELINE)
																.addComponent(jRadioButtonCORRIENTE)
																.addComponent(jRadioButtonEMPRESARIAL)
																.addComponent(jRadioButtonAHORRO))
												.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE)));

		jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/banner.png"))); // NOI18N

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)
								.addGroup(layout.createSequentialGroup().addGap(99, 99, 99).addComponent(jLabel5,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE))
								.addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE))
						.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap().addComponent(jLabel5)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(63, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void BCrearCuentaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BCrearCuentaActionPerformed
		try {
			if (clienteBuscado != null) {
				Cuenta acc = new Cuenta();
				acc.setCancelada(false);
				acc.setCliente(clienteBuscado);
				acc.setSaldo(1000);
				acc.setNumero(tfNumeroCuenta.getText());
				acc.setContrasena(new String(tfPasswordCuenta.getPassword()));
				//
				if (jRadioButtonAHORRO.isSelected()) {
					TipoCuenta tip = new TipoCuenta();
					tip.setId(1);
					acc.setTipoCuenta(tip);
				}

				if (jRadioButtonCORRIENTE.isSelected()) {
					TipoCuenta tip = new TipoCuenta();
					tip.setId(2);
					acc.setTipoCuenta(tip);
				}

				if (jRadioButtonEMPRESARIAL.isSelected()) {
					TipoCuenta tip = new TipoCuenta();
					tip.setId(3);
					acc.setTipoCuenta(tip);
				}

				controlador.crearCuenta(acc);
				JOptionPane.showMessageDialog(null, "Cuenta creada");

				// acc.set
			} else {
				JOptionPane.showMessageDialog(null, "Busca cliente!!!!", "Busca cliente!!!!",
						JOptionPane.ERROR_MESSAGE);
			}
		} catch (ExcepcionNegocio ecx) {
			JOptionPane.showMessageDialog(null, ecx.getMessage(), "Error de negocio", JOptionPane.ERROR_MESSAGE);

		} catch (Exception e) {
			e.printStackTrace();
		}

	}

	private void BBuscarCLienteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BBuscarCLienteActionPerformed
		try {
			String cedula = tfCEdulaCLiente.getText();
			Cliente cli = controlador.buscarCliente(cedula);
			if (cli != null) {
				tfNombreCliente.setText(cli.getNombre());
				double saldoTotal = controlador.sumaSaldosCLiente(cedula);
				jTextFieldTOTALDINERO.setText(String.valueOf(saldoTotal));
				llenarTablaCuentas(cedula);
				clienteBuscado = cli;

			} else {
				JOptionPane.showMessageDialog(null, "No existe", "No existe", JOptionPane.ERROR_MESSAGE);
			}
		} catch (ExcepcionNegocio exc) {
			JOptionPane.showMessageDialog(null, exc.getMessage(), "Error de negocio", JOptionPane.ERROR_MESSAGE);
		} catch (Exception exc) {
			exc.printStackTrace();
		}

	}

	public void llenarTablaCuentas(String cedula) throws Exception {
		DefaultTableModel dtm = (DefaultTableModel) tablaCuentasClientes.getModel();
		dtm.setRowCount(0);

		List<Cuenta> cuentas = controlador.listarCuentasCliente(cedula);
		for (Cuenta cuenta : cuentas) {
			dtm.addRow(new Object[] { cuenta.getNumero(), cuenta.getSaldo() });
		}

	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton BBuscarCLiente;
	private javax.swing.JButton BCrearCuenta;
	private javax.swing.ButtonGroup buttonGroup1;
	private javax.swing.ButtonGroup buttonGroup2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JRadioButton jRadioButtonAHORRO;
	private javax.swing.JRadioButton jRadioButtonCORRIENTE;
	private javax.swing.JRadioButton jRadioButtonEMPRESARIAL;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTextField jTextFieldTOTALDINERO;
	private javax.swing.JTable tablaCuentasClientes;
	private javax.swing.JTextField tfCEdulaCLiente;
	private javax.swing.JTextField tfNombreCliente;
	private javax.swing.JTextField tfNumeroCuenta;
	private javax.swing.JPasswordField tfPasswordCuenta;
	// End of variables declaration//GEN-END:variables

	public void llenartabla() {

	}
}
