/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VentanaCLientes.java
 *
 * Created on 15/08/2010, 01:12:14 PM
 */
package co.edu.eam.diseno.banco.vista.gui;

import java.util.List;

import javax.swing.table.DefaultTableModel;

import co.edu.eam.ingesoft.desarrollo.banco.persistencia.dao.definiciones.IDAOCliente;
import co.edu.eam.ingesoft.desarrollo.banco.persistencia.dao.implementacion.jdbc.DAOClienteJDBC;
import co.edu.eam.ingesoft.desarrollo.banco.persistencia.modelo.entidades.Cliente;

/**
 *
 * @author Camilo Andres
 */
public class VentanaCLientes extends javax.swing.JInternalFrame {

	private IDAOCliente dao;

	/** Creates new form VentanaCrearEditarCliente */
	public VentanaCLientes() {
		dao = new DAOClienteJDBC();
		initComponents();
		setMaximizable(false);
		setResizable(false);
		setIconifiable(true);
		setVisible(true);
		setClosable(true);

		llenartabla();

	}

	public void llenartabla() {

		try {
			List<Cliente> lista = dao.listarTodos();

			DefaultTableModel dtm = (DefaultTableModel) tablaCLiente.getModel();
			dtm.setRowCount(0);
			for (Cliente cliente : lista) {
				dtm.addRow(new Object[] { cliente.getNombre(), cliente.getCedula(), "N/A", cliente.getTelefono(),
						cliente.getDireccion() });
			}

		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		tablaCLiente = new javax.swing.JTable();

		setTitle("Lista de Clientes");
		setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/people.png"))); // NOI18N

		jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12));
		jLabel1.setText("Listado de Clientes");

		jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/banner.png"))); // NOI18N

		tablaCLiente.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, null, null, null, null }, { null, null, null, null, null },
						{ null, null, null, null, null }, { null, null, null, null, null } },
				new String[] { "Nombre", "Cedula", "Password", "Telefono", "Direccion" }) {
			boolean[] canEdit = new boolean[] { false, false, false, false, false };

			public boolean isCellEditable(int rowIndex, int columnIndex) {
				return canEdit[columnIndex];
			}
		});
		jScrollPane1.setViewportView(tablaCLiente);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup().addContainerGap()
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 538,
												Short.MAX_VALUE)
										.addComponent(jLabel1).addComponent(jScrollPane1,
												javax.swing.GroupLayout.Alignment.TRAILING,
												javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE))
								.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap().addComponent(jLabel2).addGap(17, 17, 17)
						.addComponent(jLabel1).addGap(18, 18, 18)
						.addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
						.addContainerGap()));

		pack();
	}// </editor-fold>//GEN-END:initComponents
		// Variables declaration - do not modify//GEN-BEGIN:variables

	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable tablaCLiente;
	// End of variables declaration//GEN-END:variables
}
