/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.eam.disenosoft.universidad.vista.gui;

import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import co.edu.eam.disenosof.universidad.logica.excepciones.ExcepcionNegocio;
import co.edu.eam.disenosoft.universidad.contrloadores.ControladorVentanaCrearCalificacion;
import co.edu.eam.ingesoftdesarrollo.universidad.persistencia.modelo.entidades.Asignatura;
import co.edu.eam.ingesoftdesarrollo.universidad.persistencia.modelo.entidades.Curso;
import co.edu.eam.ingesoftdesarrollo.universidad.persistencia.modelo.entidades.Evaluacion;
import co.edu.eam.ingesoftdesarrollo.universidad.persistencia.modelo.entidades.SesionCurso;

/**
 *
 * @author dir_software
 */
public class VentanaCrearCalificacion extends javax.swing.JInternalFrame {

	Evaluacion evaluacionAct;
	Asignatura asignaturaEncontrada;
	ControladorVentanaCrearCalificacion controlador;

	/**
	 * Creates new form VentanaCrearCalificacion
	 */
	public VentanaCrearCalificacion() {
		controlador = new ControladorVentanaCrearCalificacion();
		asignaturaEncontrada = null;
		evaluacionAct = null;
		initComponents();
		setVisible(true);
		setMaximizable(false);
		setIconifiable(true);
		setResizable(false);
		setClosable(true);

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		tfcodigoasignatura = new javax.swing.JTextField();
		btnBuscarAsignatura = new javax.swing.JButton();
		jLabel2 = new javax.swing.JLabel();
		tfnombreasignatura = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		jComboCurso = new javax.swing.JComboBox();
		jLabel4 = new javax.swing.JLabel();
		jPanel2 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		tablaCalificaciones = new javax.swing.JTable();
		jLabel5 = new javax.swing.JLabel();
		tfnombrecal = new javax.swing.JTextField();
		jLabel6 = new javax.swing.JLabel();
		tfnombrepor = new javax.swing.JTextField();
		jLabel7 = new javax.swing.JLabel();
		tfporcentajenoasignado = new javax.swing.JTextField();
		jBCrearCalificacion = new javax.swing.JButton();
		btnQuitarCalificacion = new javax.swing.JButton();
		jLabel8 = new javax.swing.JLabel();
		jTcodigoEval = new javax.swing.JTextField();

		setTitle("Administrar Calificaciones Curso");
		setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/a10icono.png"))); // NOI18N

		jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Asignatura"));

		jLabel1.setText("Codigo");

		btnBuscarAsignatura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/zoom37.png"))); // NOI18N
		btnBuscarAsignatura.setToolTipText("Buscar Asignatura");
		btnBuscarAsignatura.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnBuscarAsignaturaActionPerformed(evt);
			}
		});

		jLabel2.setText("Nombre");

		tfnombreasignatura.setEditable(false);

		jLabel3.setText("Curso");

		jComboCurso.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione una opcion:" }));
		jComboCurso.addItemListener(new java.awt.event.ItemListener() {
			public void itemStateChanged(java.awt.event.ItemEvent evt) {
				jComboCursoItemStateChanged(evt);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(
						jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel1Layout
										.createSequentialGroup().addContainerGap().addGroup(jPanel1Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
												.addGroup(jPanel1Layout.createSequentialGroup().addComponent(jLabel1)
														.addGap(37, 37, 37).addComponent(tfcodigoasignatura,
																javax.swing.GroupLayout.PREFERRED_SIZE, 231,
																javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(jPanel1Layout
														.createSequentialGroup()
														.addGroup(jPanel1Layout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING)
																.addComponent(jLabel2).addComponent(jLabel3))
														.addGap(33, 33, 33)
														.addGroup(jPanel1Layout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING)
																.addComponent(tfnombreasignatura)
																.addComponent(jComboCurso, 0,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		Short.MAX_VALUE))))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(btnBuscarAsignatura, javax.swing.GroupLayout.PREFERRED_SIZE, 88,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addGap(5, 5, 5).addGroup(jPanel1Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
						.addComponent(btnBuscarAsignatura, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGroup(jPanel1Layout.createSequentialGroup()
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel1).addComponent(tfcodigoasignatura,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(tfnombreasignatura, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabel2))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel3).addComponent(jComboCurso,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE))))
						.addContainerGap(29, Short.MAX_VALUE)));

		jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/a10.png"))); // NOI18N

		jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Calificaciones Curso"));

		tablaCalificaciones.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, null }, { null, null }, { null, null }, { null, null } },
				new String[] { "Nombre", "Porcentaje" }));
		jScrollPane1.setViewportView(tablaCalificaciones);

		jLabel5.setText("Nombre");

		jLabel6.setText("Porcentaje");

		jLabel7.setText("No Asignado");

		tfporcentajenoasignado.setEditable(false);
		tfporcentajenoasignado.setToolTipText("Porcentaje faltante por asignar");

		jBCrearCalificacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/calculation1.png"))); // NOI18N
		jBCrearCalificacion.setToolTipText("Agregar Calificacion");
		jBCrearCalificacion.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jBCrearCalificacionActionPerformed(evt);
			}
		});

		btnQuitarCalificacion
				.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/multiplication.png"))); // NOI18N
		btnQuitarCalificacion.setToolTipText("Quitar Calificacion Seleccionada");
		btnQuitarCalificacion.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnQuitarCalificacionActionPerformed(evt);
			}
		});

		jLabel8.setText("Codigo:");

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout
				.setHorizontalGroup(
						jPanel2Layout
								.createParallelGroup(
										javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel2Layout.createSequentialGroup().addContainerGap().addGroup(jPanel2Layout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(jPanel2Layout.createSequentialGroup().addGroup(jPanel2Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jLabel5).addComponent(jLabel6).addComponent(jLabel7)
												.addComponent(jLabel8))
												.addGap(21, 21, 21)
												.addGroup(jPanel2Layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addComponent(tfporcentajenoasignado,
																javax.swing.GroupLayout.DEFAULT_SIZE, 247,
																Short.MAX_VALUE)
														.addComponent(tfnombrepor)
														.addComponent(tfnombrecal, javax.swing.GroupLayout.DEFAULT_SIZE,
																247, Short.MAX_VALUE)
														.addComponent(jTcodigoEval))
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
												.addComponent(jBCrearCalificacion,
														javax.swing.GroupLayout.PREFERRED_SIZE, 74,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 574,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(btnQuitarCalificacion))
										.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup().addGroup(jPanel2Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel2Layout.createSequentialGroup().addGap(27, 27, 27).addComponent(
								jBCrearCalificacion, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE))
						.addGroup(jPanel2Layout.createSequentialGroup()
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
										.addComponent(jTcodigoEval, javax.swing.GroupLayout.Alignment.TRAILING,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(tfnombrecal, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabel5))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(tfnombrepor, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabel6))))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(tfporcentajenoasignado, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel7))
						.addGap(21, 21, 21)
						.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(btnQuitarCalificacion).addContainerGap(15, Short.MAX_VALUE)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup()
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
						.addGroup(layout.createSequentialGroup().addContainerGap().addComponent(jPanel2,
								javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
								.addGap(34, 34, 34).addComponent(jLabel4).addGap(18, 18, 18).addComponent(jPanel1,
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)))
				.addGap(0, 18, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 153,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addContainerGap()));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jComboCursoItemStateChanged(java.awt.event.ItemEvent evt) {// GEN-FIRST:event_jComboCursoItemStateChanged
		try {
			int pos = jComboCurso.getSelectedIndex();
			if (pos != 0) {
				Curso curso = (Curso) jComboCurso.getSelectedItem();
				double sum = controlador.porcentaje(curso);
				double res = 100 - sum;
				tfporcentajenoasignado.setText(String.valueOf(res));
				llenarTablaSesion(curso);
			}

		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	private void jBCrearCalificacionActionPerformed(java.awt.event.ActionEvent evt) {

		try {
			if (jComboCurso.getSelectedIndex() == 0) {
				JOptionPane.showMessageDialog(null, "Debe seleccionar un curso del combo");
			} else {
			int codigoEval = Integer.parseInt(jTcodigoEval.getText() + "");
			String nomEval = tfnombrecal.getText();
			double porcentaje = Double.parseDouble(tfnombrepor.getText() + "");
			Curso curso = (Curso) jComboCurso.getSelectedItem();
			
			Evaluacion eval = new Evaluacion(codigoEval, curso, nomEval, porcentaje);
			double sumat = controlador.porcentaje(curso);
			controlador.agregarEvaluacion(eval,sumat,porcentaje);
			evaluacionAct = eval;
			llenarTablaSesion(evaluacionAct.getCurso());
			JOptionPane.showMessageDialog(null, "Se ha creado la evaluacion");
			double sumatoriaNu = controlador.porcentaje(curso);
            tfporcentajenoasignado.setText(100 - sumatoriaNu + "%");
			}
		} catch (ExcepcionNegocio ex) {
			JOptionPane.showMessageDialog(null, ex.getMessage());
		} catch (Exception e) {
			e.printStackTrace();
		}

	}

	private void btnBuscarAsignaturaActionPerformed(java.awt.event.ActionEvent evt) {
		try {

			String codigo = tfcodigoasignatura.getText();
			Asignatura as = controlador.buscarAsignatura(codigo);
			asignaturaEncontrada = as;
			if (as != null) {
				tfnombreasignatura.setText(as.getNombre());
				cargarCombo();
			} else {
				JOptionPane.showMessageDialog(null, "no se encontro la asignatura con el codigo: " + codigo);
			}
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

	}

	private void btnQuitarCalificacionActionPerformed(java.awt.event.ActionEvent evt) {
		try {

			int pos = this.tablaCalificaciones.getSelectedRow();
			Curso c = (Curso) jComboCurso.getSelectedItem();
			List<Evaluacion> lista = controlador.listarEvaluacionesEstud(c, asignaturaEncontrada);
			Evaluacion e = lista.get(pos);
			controlador.eliminarEvaluacion(e);
			JOptionPane.showMessageDialog(null, "se elimino la evaluacion");
		
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

	}

	/**
	 * carga el combo curso
	 * 
	 * @param a
	 *            la asignatura por la cual se va a buscar el curso
	 */
	public void cargarCombo() {

		try {
			System.out.println("entro");
			List<Curso> lista = controlador.listarCombo(asignaturaEncontrada);
			System.out.println(lista.get(0).getCodigo());
			jComboCurso.removeAllItems();
			jComboCurso.addItem("seleccione una opcion");
			for (int i = 0; i < lista.size(); i++) {
				jComboCurso.addItem(lista.get(i));
			}

		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

	}

	/**
	 * llena la tabla con el nombre y el porcentaje de la evaluacion
	 * 
	 * @param e
	 *            la evaluacion a la que se le va a listar
	 * @throws Exception
	 *             en caso de que ocurra un excepcion tecnica
	 */
	public void llenarTablaSesion(Curso c) throws Exception {
		DefaultTableModel dtm = (DefaultTableModel) tablaCalificaciones.getModel();
		dtm.setRowCount(0);

		java.util.List<Evaluacion> lista = controlador.listarTabla(c);
		for (Evaluacion evaluacion : lista) {
			dtm.addRow(new Object[] { evaluacion.getNombre(), evaluacion.getPorcentaje() });
		}
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnBuscarAsignatura;
	private javax.swing.JButton btnQuitarCalificacion;
	private javax.swing.JButton jBCrearCalificacion;
	private javax.swing.JComboBox jComboCurso;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTextField jTcodigoEval;
	private javax.swing.JTable tablaCalificaciones;
	private javax.swing.JTextField tfcodigoasignatura;
	private javax.swing.JTextField tfnombreasignatura;
	private javax.swing.JTextField tfnombrecal;
	private javax.swing.JTextField tfnombrepor;
	private javax.swing.JTextField tfporcentajenoasignado;
	// End of variables declaration//GEN-END:variables
}
