/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.eam.disenosoft.universidad.vista.gui;

import java.nio.charset.CodingErrorAction;
import java.util.ArrayList;

import javax.persistence.PersistenceException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import antlr.collections.List;
import co.edu.eam.disenosof.universidad.logica.excepciones.ExcepcionNegocio;
import co.edu.eam.disenosoft.universidad.contrloadores.ControladorVentanaCrearCurso;
import co.edu.eam.disenosoft.universidad.modelo.enumeraciones.DiaEnum;
import co.edu.eam.disenosoft.universidad.modelo.enumeraciones.TipoAsignaturaEnum;
import co.edu.eam.ingesoftdesarrollo.universidad.persistencia.dao.definiciones.IDAOSesionCurso;
import co.edu.eam.ingesoftdesarrollo.universidad.persistencia.dao.implementacion.jpa.DAOSesionCurso;
import co.edu.eam.ingesoftdesarrollo.universidad.persistencia.modelo.entidades.Asignatura;
import co.edu.eam.ingesoftdesarrollo.universidad.persistencia.modelo.entidades.Curso;
import co.edu.eam.ingesoftdesarrollo.universidad.persistencia.modelo.entidades.Profesion;
import co.edu.eam.ingesoftdesarrollo.universidad.persistencia.modelo.entidades.Profesor;
import co.edu.eam.ingesoftdesarrollo.universidad.persistencia.modelo.entidades.SesionCurso;

/**
 *
 * @author dir_software
 */
public class VentanaCrearCurso extends javax.swing.JInternalFrame {

	private ControladorVentanaCrearCurso controlador;

	private Curso cursoActual;
	private SesionCurso sesionActul;

	/**
	 * Creates new form VentanaCrearCurso
	 */
	public VentanaCrearCurso() {
		initComponents();
		setClosable(true);
		sesionActul = null;
		cursoActual = null;
		setVisible(true);
		setMaximizable(false);
		setIconifiable(true);
		setResizable(false);
		controlador = new ControladorVentanaCrearCurso();

		comboDia.addItem("Seleccione una opcion");
		comboDia.addItem(DiaEnum.LUNES);
		comboDia.addItem(DiaEnum.MARTES);
		comboDia.addItem(DiaEnum.MIERCOLES);
		comboDia.addItem(DiaEnum.JUEVES);
		comboDia.addItem(DiaEnum.VIERNES);
		comboDia.addItem(DiaEnum.SABADO);
		comboDia.addItem(DiaEnum.DOMINGO);

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		tfcodigoasignatura = new javax.swing.JTextField();
		btnBuscarAsignatura = new javax.swing.JButton();
		jLabel2 = new javax.swing.JLabel();
		tfnombreasignatura = new javax.swing.JTextField();
		jPanel2 = new javax.swing.JPanel();
		jLabel3 = new javax.swing.JLabel();
		tfceduladocente = new javax.swing.JTextField();
		btnBuscarDocente = new javax.swing.JButton();
		jLabel4 = new javax.swing.JLabel();
		tfnombredocente = new javax.swing.JTextField();
		jPanel3 = new javax.swing.JPanel();
		jLabel5 = new javax.swing.JLabel();
		comboDia = new javax.swing.JComboBox();
		jLabel6 = new javax.swing.JLabel();
		comboHoraInicio = new javax.swing.JComboBox();
		comboHoraFin = new javax.swing.JComboBox();
		jLabel7 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		tablaHorario = new javax.swing.JTable();
		btnAgregarSesion = new javax.swing.JButton();
		jLabel8 = new javax.swing.JLabel();
		jTIdSesion = new javax.swing.JTextField();
		jPanel5 = new javax.swing.JPanel();
		jLabel9 = new javax.swing.JLabel();
		jTCodigoCurso = new javax.swing.JTextField();
		btnCrear = new javax.swing.JButton();
		btnBuscar = new javax.swing.JButton();
		brtnEditar = new javax.swing.JButton();
		jBEliminarDeLaTabla = new javax.swing.JButton();

		setTitle("Administrar Curso");
		setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/class.png"))); // NOI18N

		jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Asignatura"));

		jLabel1.setText("Codigo");

		btnBuscarAsignatura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/zoom37.png"))); // NOI18N
		btnBuscarAsignatura.setToolTipText("Buscar Asignatura");
		btnBuscarAsignatura.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnBuscarAsignaturaActionPerformed(evt);
			}
		});

		jLabel2.setText("Nombre");

		tfnombreasignatura.setEditable(false);

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addGap(23, 23, 23)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jLabel1).addComponent(jLabel2))
						.addGap(49, 49, 49)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(tfcodigoasignatura).addComponent(tfnombreasignatura))
						.addGap(18, 18, 18).addComponent(btnBuscarAsignatura, javax.swing.GroupLayout.PREFERRED_SIZE,
								77, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(53, 53, 53)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addGap(16, 16, 16).addGroup(jPanel1Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
						.addComponent(btnBuscarAsignatura, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGroup(jPanel1Layout.createSequentialGroup()
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel1).addComponent(tfcodigoasignatura,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel2).addComponent(tfnombreasignatura,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE))))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Docente"));

		jLabel3.setText("Cedula");

		btnBuscarDocente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/zoom37.png"))); // NOI18N
		btnBuscarDocente.setToolTipText("Buscar Docente");
		btnBuscarDocente.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnBuscarDocenteActionPerformed(evt);
			}
		});

		jLabel4.setText("Nombre");

		tfnombredocente.setEditable(false);

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup().addGap(23, 23, 23)
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jLabel3).addComponent(jLabel4))
						.addGap(49, 49, 49)
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(tfceduladocente).addComponent(tfnombredocente))
						.addGap(18, 18, 18).addComponent(btnBuscarDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 77,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(53, 53, 53)));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup().addGap(16, 16, 16).addGroup(jPanel2Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
						.addComponent(btnBuscarDocente, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGroup(jPanel2Layout.createSequentialGroup()
								.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel3).addComponent(tfceduladocente,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel4).addComponent(tfnombredocente,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE))))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Horario Asignatura"));

		jLabel5.setText("Dia");

		jLabel6.setText("Hora Inicio:");

		comboHoraInicio.setModel(new javax.swing.DefaultComboBoxModel(
				new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", " " }));

		comboHoraFin.setModel(new javax.swing.DefaultComboBoxModel(
				new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

		jLabel7.setText("Hora Fin:");

		tablaHorario
				.setModel(new javax.swing.table.DefaultTableModel(
						new Object[][] { { null, null, null, null }, { null, null, null, null },
								{ null, null, null, null }, { null, null, null, null } },
						new String[] { "Hora Inicial", "Dia", "Hora Final", "codigo" }));
		jScrollPane1.setViewportView(tablaHorario);

		btnAgregarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/calculation1.png"))); // NOI18N
		btnAgregarSesion.setToolTipText("Agregar sesion");
		btnAgregarSesion.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnAgregarSesionActionPerformed(evt);
			}
		});

		jLabel8.setText("Codigo Sesion");

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout.setHorizontalGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel3Layout.createSequentialGroup().addContainerGap()
						.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
								.addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel3Layout.createSequentialGroup().addGroup(jPanel3Layout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jLabel5).addComponent(jLabel6).addComponent(jLabel8))
										.addGap(18, 18, 18)
										.addGroup(jPanel3Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(jPanel3Layout.createSequentialGroup()
														.addComponent(comboHoraInicio,
																javax.swing.GroupLayout.PREFERRED_SIZE, 87,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
														.addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE,
																64, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
														.addComponent(comboHoraFin,
																javax.swing.GroupLayout.PREFERRED_SIZE, 90,
																javax.swing.GroupLayout.PREFERRED_SIZE))
												.addComponent(comboDia, javax.swing.GroupLayout.PREFERRED_SIZE, 261,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jTIdSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 127,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(34, 34, 34).addComponent(btnAgregarSesion,
												javax.swing.GroupLayout.PREFERRED_SIZE, 72,
												javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addContainerGap(34, Short.MAX_VALUE)));
		jPanel3Layout.setVerticalGroup(
				jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel3Layout
						.createSequentialGroup().addGroup(jPanel3Layout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel3Layout
										.createSequentialGroup()
										.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addGroup(jPanel3Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel5).addComponent(comboDia,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(jPanel3Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel6)
												.addComponent(comboHoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel7).addComponent(comboHoraFin,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(8, 8, 8)
										.addGroup(jPanel3Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jTIdSesion, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel8)))
								.addGroup(jPanel3Layout.createSequentialGroup().addGap(19, 19, 19)
										.addComponent(btnAgregarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 49,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(28, 28, 28)))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jScrollPane1,
								javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(110, 110, 110)));

		jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Curso"));

		jLabel9.setText("Codigo Curso");

		javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
		jPanel5.setLayout(jPanel5Layout);
		jPanel5Layout.setHorizontalGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel5Layout.createSequentialGroup().addGap(21, 21, 21)
						.addComponent(jLabel9).addGap(26, 26, 26).addComponent(jTCodigoCurso,
								javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(147, Short.MAX_VALUE)));
		jPanel5Layout.setVerticalGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel5Layout.createSequentialGroup().addContainerGap()
						.addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel9).addComponent(jTCodigoCurso,
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addContainerGap(18, Short.MAX_VALUE)));

		btnCrear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/calculation1.png"))); // NOI18N
		btnCrear.setToolTipText("Crear");
		btnCrear.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnCrearActionPerformed(evt);
			}
		});

		btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/zoom37.png"))); // NOI18N
		btnBuscar.setToolTipText("Buscar");
		btnBuscar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnBuscarActionPerformed(evt);
			}
		});

		brtnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pen38.png"))); // NOI18N
		brtnEditar.setToolTipText("Editar");
		brtnEditar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				brtnEditarActionPerformed(evt);
			}
		});

		jBEliminarDeLaTabla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/calculation.png"))); // NOI18N
		jBEliminarDeLaTabla.setToolTipText("Quitar Sesion");
		jBEliminarDeLaTabla.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jBEliminarDeLaTablaActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup()
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
						.createSequentialGroup().addContainerGap()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)
								.addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)
								.addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
						.addGroup(layout.createSequentialGroup().addGap(111, 111, 111)
								.addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 87,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(18, 18, 18)
								.addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 95,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(26, 26, 26).addComponent(brtnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 89,
										javax.swing.GroupLayout.PREFERRED_SIZE)))
				.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup().addGap(0, 23, Short.MAX_VALUE)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(layout.createSequentialGroup().addGap(10, 10, 10).addComponent(
												jBEliminarDeLaTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 67,
												javax.swing.GroupLayout.PREFERRED_SIZE))
										.addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE))));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 31,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
								.addComponent(brtnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 242,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jBEliminarDeLaTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 24,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void btnBuscarAsignaturaActionPerformed(java.awt.event.ActionEvent evt) {

		try {
			String cod = tfcodigoasignatura.getText();
			Asignatura as = controlador.buscarAsignatura(cod);
			if (as != null) {
				tfcodigoasignatura.setText(as.getCodigo());
				tfnombreasignatura.setText(as.getNombre());
			} else {
				JOptionPane.showMessageDialog(null, "la asignatura con el codigo " + cod + "no existe");
			}
		} catch (Exception exc) {
			exc.printStackTrace();
		}

	}

	private void btnBuscarDocenteActionPerformed(java.awt.event.ActionEvent evt) {
		try {
			String ced = tfceduladocente.getText();
			Profesor prof;
			prof = controlador.buscarProfesor(ced);

			if (prof != null) {
				tfceduladocente.setText(prof.getCedula());
				tfnombredocente.setText(prof.getNombre());
			} else {
				JOptionPane.showMessageDialog(null, "el profesor con la cedula " + ced + " no se encuentra registrado");
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	private void btnAgregarSesionActionPerformed(java.awt.event.ActionEvent evt) {

		try {
			if (jTCodigoCurso.getText().isEmpty()) {
				JOptionPane.showMessageDialog(null,
						"para poder agregar una sesion debe haber buscado el curso o registrado un curso");
			} else {
				DiaEnum dia = (DiaEnum) comboDia.getSelectedItem();
				int horaIn = Integer.parseInt((String) comboHoraInicio.getSelectedItem());
				int horaFin = Integer.parseInt((String) comboHoraFin.getSelectedItem());
				int cod = Integer.parseInt(jTIdSesion.getText());
				String codCurso = jTCodigoCurso.getText();
				Curso codCur = controlador.buscarCurso(codCurso);
				SesionCurso sesion = controlador.buscarSesion(cod);
				if (sesion != null) {
					JOptionPane.showMessageDialog(null, "este codigo de sesion ya esta registrado");
				} else {
					SesionCurso ses = new SesionCurso(cod, codCur, dia, horaIn, horaFin);
					controlador.crearSesionCurso(ses);
					sesionActul = ses;
					codCur.getSesiones().add(sesionActul);
					JOptionPane.showMessageDialog(null, "Se ha creado la sesion");
					llenarTablaSesion();
				}
			}
		} catch (ExcepcionNegocio ex) {
			JOptionPane.showMessageDialog(null, ex.getMessage());
		} catch (PersistenceException e) {
			// TODO Auto-generated catch block
			JOptionPane.showMessageDialog(null, "el codigo ya existe");
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	private void jBEliminarDeLaTablaActionPerformed(java.awt.event.ActionEvent evt) {

		try {
			int pos = this.tablaHorario.getSelectedRow();
			if (pos >= 0) {
				cursoActual.getSesiones().remove(pos);
				controlador.eliminarSesion(cursoActual);
				llenarTablaSesion();
				JOptionPane.showMessageDialog(null, "se ha eliminado la sesion");
			} else {
				JOptionPane.showMessageDialog(null, "seleccione la fila que quiere registrar");

			}

		} catch (Exception e) {
			e.printStackTrace();
		}

	}

	private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {

		try {
			if (tfcodigoasignatura.getText().isEmpty() || tfceduladocente.getText().isEmpty()
					|| jTCodigoCurso.getText().isEmpty()) {

				JOptionPane.showMessageDialog(null, "verifique que todos los campos esten didligenciados");
			} else {
				String codAsig = tfcodigoasignatura.getText();
				Asignatura asig = controlador.buscarAsignatura(codAsig);
				String cedProf = tfceduladocente.getText();
				Profesor prof = controlador.buscarProfesor(cedProf);
				String idCurs = jTCodigoCurso.getText();

				Curso cur = new Curso(idCurs, prof, asig);
				controlador.crearCurso(cur);
				JOptionPane.showMessageDialog(null, "Se ha generado el curso");
			}
		} catch (ExcepcionNegocio exc) {
			JOptionPane.showMessageDialog(null, exc.getMessage());
		} catch (Exception e) {
			e.printStackTrace();
		}

	}

	private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {

		try {
			if (jTCodigoCurso.getText().isEmpty()) {
				JOptionPane.showMessageDialog(null, "por favor ingrese el codigo del curso a buscar");

			} else {
				String idCurs = jTCodigoCurso.getText();
				Curso cur = controlador.buscarCurso(idCurs);
				cursoActual = cur;
				if (idCurs != null) {
					tfcodigoasignatura.setText(cur.getAsignatura().getCodigo());
					tfceduladocente.setText(cur.getDocente().getCedula());
					jTCodigoCurso.setText(cur.getCodigo());
					llenarTablaSesion();

				}
			}
		} catch (Exception e) {
			e.printStackTrace();
		}

	}

	private void brtnEditarActionPerformed(java.awt.event.ActionEvent evt) {
		try {
			
			
		if(cursoActual != null){
			
			String ced = tfceduladocente.getText();
			Profesor p = controlador.buscarProfesor(ced);
			cursoActual.setDocente(p);
			
			String as = tfcodigoasignatura.getText();
			Asignatura asig = controlador.buscarAsignatura(as);
			cursoActual.setAsignatura(asig);
			
			String codCur = jTCodigoCurso.getText();
			cursoActual.setCodigo(codCur);
			
			controlador.editarCurso(cursoActual);
			JOptionPane.showMessageDialog(null, "se edito el curso correctamente");
			
			
			}else{
				JOptionPane.showMessageDialog(null, "se debe buscar el curso antes de editarlo");
			}
		
			} catch(ExcepcionNegocio ex){
				ex.getMessage();
				
			}catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			
				
			
			
			
		
		
		
		
		
		
		
	}

	/**
	 * llena la tabla con el dia la hora inicial y hora final
	 * 
	 * @throws Exception
	 *             en caso de que ocurra un excepcion tecnica
	 */
	public void llenarTablaSesion() throws Exception {
		DefaultTableModel dtm = (DefaultTableModel) tablaHorario.getModel();
		dtm.setRowCount(0);

		java.util.List<SesionCurso> sesion = cursoActual.getSesiones();
		for (SesionCurso sesionCurso : sesion) {
			dtm.addRow(new Object[] { sesionCurso.getDia(), sesionCurso.getHoraInicio(), sesionCurso.getHoraFinal(),
					sesionCurso.getCodigoSesionCur() });
		}
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton brtnEditar;
	private javax.swing.JButton btnAgregarSesion;
	private javax.swing.JButton btnBuscar;
	private javax.swing.JButton btnBuscarAsignatura;
	private javax.swing.JButton btnBuscarDocente;
	private javax.swing.JButton btnCrear;
	private javax.swing.JComboBox comboDia;
	private javax.swing.JComboBox comboHoraFin;
	private javax.swing.JComboBox comboHoraInicio;
	private javax.swing.JButton jBEliminarDeLaTabla;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel5;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTextField jTCodigoCurso;
	private javax.swing.JTextField jTIdSesion;
	private javax.swing.JTable tablaHorario;
	private javax.swing.JTextField tfceduladocente;
	private javax.swing.JTextField tfcodigoasignatura;
	private javax.swing.JTextField tfnombreasignatura;
	private javax.swing.JTextField tfnombredocente;
	// End of variables declaration//GEN-END:variables

}
