/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.eam.ingesoft.desarrollo.vista.gui;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import co.edu.eam.desarrollo.proyectoFinal.gui.controladores.ControladorVentanaEgresado;
import co.edu.eam.desarrollo.proyectoFinal.implementaciones.DAOEgresado;
import co.edu.eam.desarrolloSoftware.proyectoFinal.enumeraciones.NivelAcademico;
import co.edu.eam.desarrolloSoftware.proyectoFinal.enumeraciones.SituacionActual;
import co.edu.eam.desarrolloSoftware.proyectoFinal.enumeraciones.TipoDocumento;
import co.edu.eam.desarrolloSoftware.proyectoFinal.enumeraciones.TipoEmpresa;
import co.edu.eam.desarrolloSoftware.proyectoFinal.modelo.AreaInteres;
import co.edu.eam.desarrolloSoftware.proyectoFinal.modelo.AreasEgresado;
import co.edu.eam.desarrolloSoftware.proyectoFinal.modelo.Egresado;
import co.edu.eam.desarrolloSoftware.proyectoFinal.modelo.Empresa;
import co.edu.eam.desarrolloSoftware.proyectoFinal.modelo.Facultad;
import co.edu.eam.desarrolloSoftware.proyectoFinal.modelo.HistorialLaboral;
import co.edu.eam.desarrolloSoftware.proyectoFinal.modelo.InformacionAcademica;
import co.edu.eam.desarrolloSoftware.proyectoFinal.modelo.InformacionLaboral;
import co.edu.eam.desarrolloSoftware.proyectoFinal.modelo.Programa;
import co.edu.eam.desarrolloSoftware.proyectoFinal.modelo.SectorLaboral;

/**
 *
 * @author Carlos Alfredo Martinez Villada 
 */
public class Egresados extends javax.swing.JFrame {

	private ControladorVentanaEgresado controlador;
    private int selec = 0; // indicara cual es la pestaña seleccionada inicialmente
    public Egresados() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setIconImage(new ImageIcon(getClass().getResource("/imagenes/icono.png")).getImage());
        this.setTitle("Registro de Egresados");
        jTabbedPane1.setEnabledAt(1, false);
        jTabbedPane1.setEnabledAt(2, false);
        jTabbedPane1.setEnabledAt(3, false);
        jBAnterior.setVisible(false);
        controlador = new ControladorVentanaEgresado();
        /* cargamos constantes en los combos */
        /* Tipo de documento */
        jCBDocumento1.addItem(TipoDocumento.CEDULA);
        jCBDocumento1.addItem(TipoDocumento.PASAPORTE);
        jCBDocumento1.addItem(TipoDocumento.TI);
        /* Nivel Academico */
        jCNivelAcad.addItem(NivelAcademico.PREGRADO);
        jCNivelAcad.addItem(NivelAcademico.POSTGRADO);
        jCNivelAcad.addItem(NivelAcademico.DIPLOMADO);
        /* Situacion Actual */
        jCSituacionActual.addItem(SituacionActual.EMPLEADO);
        jCSituacionActual.addItem(SituacionActual.DESEMPLEADO);
        jCSituacionActual.addItem(SituacionActual.EMPRESARIO);
        jCSituacionActual.addItem(SituacionActual.INDEPENDIENTE);
        /* Tipo Empresa */
        jCEmpresa.addItem(TipoEmpresa.PRIVADA);
        jCEmpresa.addItem(TipoEmpresa.PUBLICA);
        /* Cargamos los Combos */
        cargarFacultades();
        cargarEmpresas();
        /* Llenamos la tabla Areas de conocimiento*/
        cargarAreasConocimiento();
        /* Ocultamos elementos que no deben aparecer inicialmente */
        jBEliminarInteres.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTNumeroDocumento = new javax.swing.JTextField();
        jLnumeroDocumento = new javax.swing.JLabel();
        jTCorreo = new javax.swing.JTextField();
        jLcorreo = new javax.swing.JLabel();
        jTTelefono = new javax.swing.JTextField();
        jLtelefono = new javax.swing.JLabel();
        jLcelular = new javax.swing.JLabel();
        jTCelular = new javax.swing.JTextField();
        jLnombre6 = new javax.swing.JLabel();
        jTnombre1 = new javax.swing.JTextField();
        jLTipoDocumento1 = new javax.swing.JLabel();
        jTapellido1 = new javax.swing.JTextField();
        jLApellido1 = new javax.swing.JLabel();
        jCBDocumento1 = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLFacultad = new javax.swing.JLabel();
        jLPrograma = new javax.swing.JLabel();
        jLFecha = new javax.swing.JLabel();
        jDateFechaGrado = new com.toedter.calendar.JDateChooser();
        jLNivel = new javax.swing.JLabel();
        jLNumero = new javax.swing.JLabel();
        jCFacultad = new javax.swing.JComboBox();
        jCPrograma = new javax.swing.JComboBox();
        jCNivelAcad = new javax.swing.JComboBox();
        jTNDiploma = new javax.swing.JTextField();
        jBHome1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jCSituacionActual = new javax.swing.JComboBox();
        jLFacultad1 = new javax.swing.JLabel();
        jCEmpresa = new javax.swing.JComboBox();
        jLFacultad2 = new javax.swing.JLabel();
        jLnombre3 = new javax.swing.JLabel();
        jDateSalida = new com.toedter.calendar.JDateChooser();
        jDateIngreso = new com.toedter.calendar.JDateChooser();
        jLnombre4 = new javax.swing.JLabel();
        jLnombre5 = new javax.swing.JLabel();
        jTCargo = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAreasConocimiento = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableAreasConocimiento1 = new javax.swing.JTable();
        jBAgregarInteres = new javax.swing.JButton();
        jBEliminarInteres = new javax.swing.JButton();
        jBAgregarPalabra = new javax.swing.JButton();
        jBcANCELAR = new javax.swing.JButton();
        jBSiguiente = new javax.swing.JButton();
        jBBuscar = new javax.swing.JButton();
        jBEditar = new javax.swing.JButton();
        jBEliminar = new javax.swing.JButton();
        jBAnterior = new javax.swing.JButton();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel8.setBackground(new java.awt.Color(242, 242, 249));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(48, 43, 43));
        jLabel1.setText("Informacion personal del Egresado");

        jTNumeroDocumento.setBackground(new java.awt.Color(242, 242, 249));
        jTNumeroDocumento.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jTNumeroDocumento.setForeground(new java.awt.Color(43, 43, 74));
        jTNumeroDocumento.setToolTipText("");
        jTNumeroDocumento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(232, 232, 240)));
        jTNumeroDocumento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTNumeroDocumentoKeyTyped(evt);
            }
        });

        jLnumeroDocumento.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLnumeroDocumento.setForeground(new java.awt.Color(51, 51, 51));
        jLnumeroDocumento.setText("Numero de Documento");

        jTCorreo.setBackground(new java.awt.Color(242, 242, 249));
        jTCorreo.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jTCorreo.setForeground(new java.awt.Color(43, 43, 74));
        jTCorreo.setToolTipText("");
        jTCorreo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(232, 232, 240)));

        jLcorreo.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLcorreo.setForeground(new java.awt.Color(51, 51, 51));
        jLcorreo.setText("Correo Electronico");

        jTTelefono.setBackground(new java.awt.Color(242, 242, 249));
        jTTelefono.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jTTelefono.setForeground(new java.awt.Color(43, 43, 74));
        jTTelefono.setToolTipText("");
        jTTelefono.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(232, 232, 240)));
        jTTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTTelefonoKeyTyped(evt);
            }
        });

        jLtelefono.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLtelefono.setForeground(new java.awt.Color(51, 51, 51));
        jLtelefono.setText("Telefono");

        jLcelular.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLcelular.setForeground(new java.awt.Color(51, 51, 51));
        jLcelular.setText("Celular");

        jTCelular.setBackground(new java.awt.Color(242, 242, 249));
        jTCelular.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jTCelular.setForeground(new java.awt.Color(43, 43, 74));
        jTCelular.setToolTipText("");
        jTCelular.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(232, 232, 240)));
        jTCelular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTCelularKeyTyped(evt);
            }
        });

        jLnombre6.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLnombre6.setForeground(new java.awt.Color(51, 51, 51));
        jLnombre6.setText("Nombre");

        jTnombre1.setBackground(new java.awt.Color(242, 242, 249));
        jTnombre1.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jTnombre1.setForeground(new java.awt.Color(43, 43, 74));
        jTnombre1.setToolTipText("");
        jTnombre1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(232, 232, 240)));
        jTnombre1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTnombre1KeyTyped(evt);
            }
        });

        jLTipoDocumento1.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLTipoDocumento1.setForeground(new java.awt.Color(51, 51, 51));
        jLTipoDocumento1.setText("Tipo Documento");

        jTapellido1.setBackground(new java.awt.Color(242, 242, 249));
        jTapellido1.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jTapellido1.setForeground(new java.awt.Color(43, 43, 74));
        jTapellido1.setToolTipText("");
        jTapellido1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(232, 232, 240)));
        jTapellido1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTapellido1KeyTyped(evt);
            }
        });

        jLApellido1.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLApellido1.setForeground(new java.awt.Color(51, 51, 51));
        jLApellido1.setText("Apellido");

        jCBDocumento1.setBackground(new java.awt.Color(242, 242, 249));
        jCBDocumento1.setBorder(null);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLTipoDocumento1)
                            .addComponent(jLnumeroDocumento))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTNumeroDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCBDocumento1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLApellido1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTapellido1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLnombre6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTnombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(1, 1, 1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLcorreo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLcelular)
                            .addComponent(jLtelefono))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTCelular, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTTelefono, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLnombre6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTnombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTapellido1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCBDocumento1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLTipoDocumento1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLnumeroDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTNumeroDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLtelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLcelular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Datos Personales", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(48, 43, 43));
        jLabel2.setText("Informacion Academica");

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLFacultad.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLFacultad.setForeground(new java.awt.Color(51, 51, 51));
        jLFacultad.setText("Facultad");

        jLPrograma.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLPrograma.setForeground(new java.awt.Color(51, 51, 51));
        jLPrograma.setText("Programa Academico");

        jLFecha.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLFecha.setForeground(new java.awt.Color(51, 51, 51));
        jLFecha.setText("Fecha de Grado");

        jDateFechaGrado.setBackground(new java.awt.Color(242, 242, 249));

        jLNivel.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLNivel.setForeground(new java.awt.Color(51, 51, 51));
        jLNivel.setText("Nivel Academico");

        jLNumero.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLNumero.setForeground(new java.awt.Color(51, 51, 51));
        jLNumero.setText("Numero del Diploma");

        jCFacultad.setBackground(new java.awt.Color(242, 242, 249));
        jCFacultad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        jCFacultad.setBorder(null);
        jCFacultad.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCFacultadItemStateChanged(evt);
            }
        });

        jCPrograma.setBackground(new java.awt.Color(242, 242, 249));
        jCPrograma.setBorder(null);

        jCNivelAcad.setBackground(new java.awt.Color(242, 242, 249));
        jCNivelAcad.setBorder(null);

        jTNDiploma.setBackground(new java.awt.Color(242, 242, 249));
        jTNDiploma.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jTNDiploma.setForeground(new java.awt.Color(43, 43, 74));
        jTNDiploma.setToolTipText("");
        jTNDiploma.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(232, 232, 240)));
        jTNDiploma.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTNDiplomaKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLPrograma)
                    .addComponent(jLNivel)
                    .addComponent(jLNumero)
                    .addComponent(jLFecha)
                    .addComponent(jLFacultad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCNivelAcad, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDateFechaGrado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                    .addComponent(jCPrograma, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCFacultad, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTNDiploma))
                .addGap(23, 23, 23))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCFacultad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLFacultad, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCPrograma, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLPrograma, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jDateFechaGrado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCNivelAcad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLNivel, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTNDiploma, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(108, Short.MAX_VALUE))
        );

        jBHome1.setBackground(new java.awt.Color(24, 185, 231));
        jBHome1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBHome1.setForeground(new java.awt.Color(255, 255, 255));
        jBHome1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(25, 174, 217), 1, true));
        jBHome1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBHome1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBHome1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(248, 248, 248)
                    .addComponent(jBHome1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(208, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(218, 218, 218)
                    .addComponent(jBHome1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(141, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Educacion", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(48, 43, 43));
        jLabel3.setText("Informacion Laboral");

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jCSituacionActual.setBackground(new java.awt.Color(242, 242, 249));
        jCSituacionActual.setBorder(null);

        jLFacultad1.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLFacultad1.setForeground(new java.awt.Color(51, 51, 51));
        jLFacultad1.setText("Situacion Actual");

        jCEmpresa.setBackground(new java.awt.Color(242, 242, 249));
        jCEmpresa.setBorder(null);

        jLFacultad2.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLFacultad2.setForeground(new java.awt.Color(51, 51, 51));
        jLFacultad2.setText("Empresa");

        jLnombre3.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLnombre3.setForeground(new java.awt.Color(51, 51, 51));
        jLnombre3.setText("Fecha de Ingreso");

        jDateSalida.setBackground(new java.awt.Color(242, 242, 249));

        jDateIngreso.setBackground(new java.awt.Color(242, 242, 249));

        jLnombre4.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLnombre4.setForeground(new java.awt.Color(51, 51, 51));
        jLnombre4.setText("Fecha de Salida");

        jLnombre5.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLnombre5.setForeground(new java.awt.Color(51, 51, 51));
        jLnombre5.setText("Cargo en la Empresa");

        jTCargo.setBackground(new java.awt.Color(242, 242, 249));
        jTCargo.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jTCargo.setForeground(new java.awt.Color(43, 43, 74));
        jTCargo.setToolTipText("");
        jTCargo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(232, 232, 240)));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLFacultad2)
                    .addComponent(jLFacultad1)
                    .addComponent(jLnombre3)
                    .addComponent(jLnombre4)
                    .addComponent(jLnombre5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jDateIngreso, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                    .addComponent(jCSituacionActual, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCEmpresa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDateSalida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTCargo))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLFacultad1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCSituacionActual, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLFacultad2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLnombre3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLnombre4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLnombre5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(118, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Ocupacion Actual", jPanel3);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jTableAreasConocimiento.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jTableAreasConocimiento.setForeground(new java.awt.Color(51, 51, 51));
        jTableAreasConocimiento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Area del conocimiento"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableAreasConocimiento.setGridColor(new java.awt.Color(239, 239, 239));
        jScrollPane1.setViewportView(jTableAreasConocimiento);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(48, 43, 43));
        jLabel5.setText("Areas de Conocimiento");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(48, 43, 43));
        jLabel6.setText("Seleccione las areas de conocimiento que sean de su interes");

        jTableAreasConocimiento1.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jTableAreasConocimiento1.setForeground(new java.awt.Color(51, 51, 51));
        jTableAreasConocimiento1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Mis areas de interes"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableAreasConocimiento1.setGridColor(new java.awt.Color(239, 239, 239));
        jScrollPane2.setViewportView(jTableAreasConocimiento1);

        jBAgregarInteres.setBackground(new java.awt.Color(175, 178, 184));
        jBAgregarInteres.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jBAgregarInteres.setForeground(new java.awt.Color(51, 51, 51));
        jBAgregarInteres.setText("Agregar");
        jBAgregarInteres.setToolTipText("Cancelar Registro");
        jBAgregarInteres.setBorder(null);
        jBAgregarInteres.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBAgregarInteres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAgregarInteresActionPerformed(evt);
            }
        });

        jBEliminarInteres.setBackground(new java.awt.Color(175, 178, 184));
        jBEliminarInteres.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jBEliminarInteres.setForeground(new java.awt.Color(51, 51, 51));
        jBEliminarInteres.setText("Eliminar");
        jBEliminarInteres.setToolTipText("Cancelar Registro");
        jBEliminarInteres.setBorder(null);
        jBEliminarInteres.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBEliminarInteres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarInteresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addContainerGap(131, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jBAgregarInteres, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBEliminarInteres, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(25, 25, 25))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(11, 11, 11)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBAgregarInteres, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBEliminarInteres, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(174, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Areas de conocimiento", jPanel7);

        jBAgregarPalabra.setBackground(new java.awt.Color(66, 183, 42));
        jBAgregarPalabra.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jBAgregarPalabra.setForeground(new java.awt.Color(255, 255, 255));
        jBAgregarPalabra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Inicio.png"))); // NOI18N
        jBAgregarPalabra.setToolTipText("Ir al inicio");
        jBAgregarPalabra.setBorder(null);
        jBAgregarPalabra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBAgregarPalabra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAgregarPalabraActionPerformed(evt);
            }
        });

        jBcANCELAR.setBackground(new java.awt.Color(66, 103, 178));
        jBcANCELAR.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jBcANCELAR.setForeground(new java.awt.Color(255, 255, 255));
        jBcANCELAR.setText("Cancelar");
        jBcANCELAR.setToolTipText("Cancelar Registro");
        jBcANCELAR.setBorder(null);
        jBcANCELAR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBcANCELAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcANCELARActionPerformed(evt);
            }
        });

        jBSiguiente.setBackground(new java.awt.Color(66, 103, 178));
        jBSiguiente.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jBSiguiente.setForeground(new java.awt.Color(255, 255, 255));
        jBSiguiente.setText("Siguiente");
        jBSiguiente.setToolTipText("Siguiente");
        jBSiguiente.setBorder(null);
        jBSiguiente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSiguienteActionPerformed(evt);
            }
        });

        jBBuscar.setBackground(new java.awt.Color(175, 178, 184));
        jBBuscar.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jBBuscar.setForeground(new java.awt.Color(255, 255, 255));
        jBBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscar.png"))); // NOI18N
        jBBuscar.setToolTipText("Buscar");
        jBBuscar.setBorder(null);
        jBBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarActionPerformed(evt);
            }
        });

        jBEditar.setBackground(new java.awt.Color(175, 178, 184));
        jBEditar.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jBEditar.setForeground(new java.awt.Color(255, 255, 255));
        jBEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Actualizar.png"))); // NOI18N
        jBEditar.setToolTipText("Editar Informacion");
        jBEditar.setBorder(null);
        jBEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEditarActionPerformed(evt);
            }
        });

        jBEliminar.setBackground(new java.awt.Color(175, 178, 184));
        jBEliminar.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jBEliminar.setForeground(new java.awt.Color(255, 255, 255));
        jBEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/delete.png"))); // NOI18N
        jBEliminar.setToolTipText("Eliminar");
        jBEliminar.setBorder(null);
        jBEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarActionPerformed(evt);
            }
        });

        jBAnterior.setBackground(new java.awt.Color(66, 103, 178));
        jBAnterior.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jBAnterior.setForeground(new java.awt.Color(255, 255, 255));
        jBAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/anterior.png"))); // NOI18N
        jBAnterior.setToolTipText("Anterior");
        jBAnterior.setBorder(null);
        jBAnterior.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAnteriorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jBAgregarPalabra, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBcANCELAR, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBAgregarPalabra, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBcANCELAR, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jBBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBHome1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBHome1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBHome1ActionPerformed

    private void jBAgregarPalabraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAgregarPalabraActionPerformed
        VentanaPrincipal vp = new VentanaPrincipal();
        vp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jBAgregarPalabraActionPerformed

    private void jBcANCELARActionPerformed(java.awt.event.ActionEvent evt) {     
        int op = JOptionPane.showConfirmDialog(null, "Seguro que desea cancelar el registro", "Cancelar Registro", JOptionPane.INFORMATION_MESSAGE); 
        if(op == 0){
        	limpiarCampos();
            jTabbedPane1.setEnabledAt(selec, false);
            selec = 0;
            jTabbedPane1.setEnabledAt(selec, true);
            jTabbedPane1.setSelectedIndex(0); 
            jBSiguiente.setText("Siguiente");
            jBSiguiente.setToolTipText("Siguiente");
            jBSiguiente.setBackground(new Color(66,103,178));
        }
    }

    private void jBSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSiguienteActionPerformed
    	switch (selec){
	        case 0:
	        	/* Informacion personal */
	        	if(jTnombre1.getText().isEmpty() || jTapellido1.getText().isEmpty() || jTCorreo.getText().isEmpty() || jTTelefono.getText().isEmpty() || jTCelular.getText().isEmpty() || jTNumeroDocumento.getText().isEmpty()){
	                JOptionPane.showMessageDialog(null, "Por favor, complete todos los campos", "Administrador de Egresados", JOptionPane.WARNING_MESSAGE); 
	                return;
	        	}
	        break;
	        case 1:
	        	/* Informacion Academica */
	        	if(jTNDiploma.getText().isEmpty() || jDateFechaGrado.getDate() == null){
	                JOptionPane.showMessageDialog(null, "Por favor, complete todos los campos", "Administrador de Egresados", JOptionPane.WARNING_MESSAGE); 
	                return;
	        	}
	        break;
	        case 2:
	        	/* Informacion laboral */
	        	if(jTCargo.getText().isEmpty() || jDateIngreso.getDate() == null || jDateSalida.getDate() == null){
	                JOptionPane.showMessageDialog(null, "Por favor, complete todos los campos", "Administrador de Egresados", JOptionPane.WARNING_MESSAGE); 
	                return;
	        	}
		    break;
	        case 3:
	        	if(misAreas.isEmpty()){
	                JOptionPane.showMessageDialog(null, "Por favor, elige al menos una area de interes", "Administrador de Egresados", JOptionPane.WARNING_MESSAGE); 
	                return;
	        	}
	        break;	
    	}
    	if(selec < 3 ){
            jTabbedPane1.setEnabledAt(selec, false);
            selec = selec + 1;
            jTabbedPane1.setEnabledAt(selec, true);
            jTabbedPane1.setSelectedIndex(selec); 
        	if(selec > 0){
        		jBAnterior.setVisible(true);
        	}else{
        		jBAnterior.setVisible(false);
        	}
            if(selec == 3){
                jBSiguiente.setText("Registrar");
                jBSiguiente.setToolTipText("Registrar Egresado");
                jBSiguiente.setBackground(new Color(66,183,42));
            }
        }else{
        	/**
        	 * Recojo toda la informacion y la guardo en variables
        	 */
        	/* Informacion personal */
        	String nombre = jTnombre1.getText();
        	String apellido = jTapellido1.getText();
        	String correo = jTCorreo.getText();
        	String telefono = jTTelefono.getText();
        	String celular = jTCelular.getText();
        	TipoDocumento tipoDocumento = (TipoDocumento) jCBDocumento1.getSelectedItem();
        	String numeroDocumento = jTNumeroDocumento.getText();
        	
        	/* Informacion Academica */
        	Facultad facultad = (Facultad)jCFacultad.getSelectedItem();
        	Programa programa = (Programa)jCPrograma.getSelectedItem();
        	Date fechaGrado = jDateFechaGrado.getDate();
        	NivelAcademico nivelAcademico = (NivelAcademico)jCNivelAcad.getSelectedItem();
        	String numeroDiploma= jTNDiploma.getText();
        	
        	/* Informacion laboral */
        	String cargo = jTCargo.getText();
        	Date fechaIngreso = jDateIngreso.getDate();
        	Date fechaSalida = jDateSalida.getDate();
        	SituacionActual situacionActual = (SituacionActual) jCSituacionActual.getSelectedItem();
        	Empresa empresa = (Empresa) jCEmpresa.getSelectedItem();
        	
        	/* Creo el objeto egresado */
        	try{
	        	Egresado e = controlador.buscarEgresadoTipo(tipoDocumento, numeroDocumento);
	        	if(e != null ){
	                JOptionPane.showMessageDialog(null, "Ya existe un egresado con el numero de documento "+numeroDocumento, "Administrador de Egresados", JOptionPane.WARNING_MESSAGE); 
	        	}else{
	        		int id = Integer.parseInt(numeroDocumento);
	        		Egresado eg = controlador.buscarEgresado(id);
	        		if(eg != null){
	        			id = id+1;
	        		}
	        		Egresado egresado = new Egresado(id, programa, nombre, apellido, correo, telefono, celular, tipoDocumento, numeroDocumento);
	        		controlador.crearEgresado(egresado, misAreas);	 
	        		InformacionLaboral informacionLaboral = new InformacionLaboral(egresado, situacionActual, fechaIngreso, fechaSalida, cargo, empresa);
	        		controlador.crearInformacionLaboral(informacionLaboral);
	        		InformacionAcademica ia = new InformacionAcademica(egresado, fechaGrado, facultad, programa, nivelAcademico, numeroDiploma);
	        		controlador.crearInformacionAcademica(ia);
//	        		HistorialLaboral hl = new HistorialLaboral(informacionLaboral, empresa);
//	        		controlador.crearHistorialLaboral(hl);
	        		    limpiarCampos();
			            jBSiguiente.setText("Registrado");
			            JOptionPane.showMessageDialog(null, "Se ha Registrado al Egresado "+egresado.getNombre()+" "+egresado.getApellido(), "Administrador de Egresados", JOptionPane.INFORMATION_MESSAGE); 
			            jTabbedPane1.setEnabledAt(selec, false);
			            selec = 0;
			            jTabbedPane1.setEnabledAt(selec, true);
			            jTabbedPane1.setSelectedIndex(selec);     
			            jBSiguiente.setText("Siguiente");
			            jBSiguiente.setToolTipText("Siguiente");
			            jBSiguiente.setBackground(new Color(66,103,178));
			            jBAnterior.setVisible(false);
	        	}
        	}catch(Exception e){
	            JOptionPane.showMessageDialog(null, "Ha ocurrido un error.", "Administrador de Egresados", JOptionPane.ERROR_MESSAGE); 
        		e.printStackTrace();
        	}
        }
    }
    /**
     * limpiar campos del registro egresados
     */
    public void limpiarCampos(){
    	jTnombre1.setText(null);
    	jTapellido1.setText(null);
    	jTCorreo.setText(null);
    	jTTelefono.setText(null);
    	jTCelular.setText(null);
    	jCBDocumento1.setSelectedIndex(0);
    	jTNumeroDocumento.setText(null);
        jCFacultad.setSelectedIndex(0);
    	jDateFechaGrado.setDate(null);
    	jCNivelAcad.setSelectedIndex(0);
    	jTNDiploma.setText(null);
    	jCPrograma.setSelectedIndex(0);
    	jDateFechaGrado.setDate(null);
    	jCNivelAcad.setSelectedIndex(0);
    	jTNDiploma.setText(null);
		jCSituacionActual.setSelectedIndex(0);
		jCEmpresa.setSelectedIndex(0);
		jDateIngreso.setDate(null);
		jDateSalida.setDate(null);
		jTCargo.setText(null);
		misAreas.clear();
		misAreasDeInteres();
    }

    private void jBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarActionPerformed
    	TipoDocumento tipoDocumento = (TipoDocumento) jCBDocumento1.getSelectedItem();
    	String numeroDocumento = jTNumeroDocumento.getText();
    	if(numeroDocumento.isEmpty()){
            JOptionPane.showMessageDialog(null, "Ingrese el numero de identificacion\ndel egresado a buscar ", "Administrador de Egresados", JOptionPane.INFORMATION_MESSAGE); 
    	}else{
    		try{
	    		Egresado e = controlador.buscarEgresadoTipo(tipoDocumento, numeroDocumento);
	    		if(e == null){
	    			misAreas = null;
	    			misAreasDeInteres();
	                JOptionPane.showMessageDialog(null, "No se ha encontrado ningun egresado\ncon el tipo de documento: "+tipoDocumento.name()+" "+numeroDocumento, "Administrador de Egresados", JOptionPane.INFORMATION_MESSAGE); 
	    		}else{
	    	    	jTnombre1.setText(e.getNombre());
	    	    	jTapellido1.setText(e.getApellido());
	    	    	jTCorreo.setText(e.getCorreo());
	    	    	jTTelefono.setText(e.getTelefono());
	    	    	jTCelular.setText(e.getCelular());
	    	    	InformacionAcademica a =controlador.buscarInfoAcademica(e.getId());
	    	    	if(a != null){
	    	    		jCFacultad.setSelectedItem(a.getFacultad());
		    	    	jDateFechaGrado.setDate(a.getFechaGrado());
		    	    	jCNivelAcad.setSelectedItem(a.getNivelAcademico());
		    	    	jTNDiploma.setText(a.getNumeroDiploma());
		    	    	jCPrograma.setSelectedItem(a.getPrograma());
	    	    	}
	    	    	InformacionLaboral l = controlador.buscarInfoLaboral(e.getId());
	    	    	if(l != null){
	    	    		jCSituacionActual.setSelectedItem(l.getSituacionActual());
	    	    		jCEmpresa.setSelectedItem(l.getEmpresa());
	    	    		jDateIngreso.setDate(l.getFechaIngreso());
	    	    		jDateSalida.setDate(l.getFechaSalida());
	    	    		jTCargo.setText(l.getCargo());
	    	    	}
	    	    	misAreas = controlador.listarAreaInteresEgresado(e);
	    	    	misAreasDeInteres();
	    	    	
	    		}
    		}catch(Exception e){
	            JOptionPane.showMessageDialog(null, "Ha ocurrido un error.", "Administrador de Egresados", JOptionPane.ERROR_MESSAGE); 
        		e.printStackTrace();
        	}
    	}
    }//GEN-LAST:event_jBBuscarActionPerformed

    private void jBEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEditarActionPerformed
    	String numeroDocumento = jTNumeroDocumento.getText();
    	if(numeroDocumento.isEmpty()){
            JOptionPane.showMessageDialog(null, "por favor, busque el egresado a editar", "Administrador de Egresados", JOptionPane.INFORMATION_MESSAGE); 
    	}else{
        	/**
        	 * Recojo toda la informacion y la guardo en variables
        	 */
        	/* Informacion personal */
        	String nombre = jTnombre1.getText();
        	String apellido = jTapellido1.getText();
        	String correo = jTCorreo.getText();
        	String telefono = jTTelefono.getText();
        	String celular = jTCelular.getText();
        	TipoDocumento tipoDocumento = (TipoDocumento) jCBDocumento1.getSelectedItem();
        	
        	/* Informacion Academica */
        	Facultad facultad = (Facultad)jCFacultad.getSelectedItem();
        	Programa programa = (Programa)jCPrograma.getSelectedItem();
        	Date fechaGrado = jDateFechaGrado.getDate();
        	NivelAcademico nivelAcademico = (NivelAcademico)jCNivelAcad.getSelectedItem();
        	String numeroDiploma= jTNDiploma.getText();
        	
        	/* Informacion laboral */
        	String cargo = jTCargo.getText();
        	Date fechaIngreso = jDateIngreso.getDate();
        	Date fechaSalida = jDateSalida.getDate();
        	SituacionActual situacionActual = (SituacionActual) jCSituacionActual.getSelectedItem();
        	Empresa empresa = (Empresa) jCEmpresa.getSelectedItem();
        	
        	/* Creo el objeto egresado */
        	try{
	        	Egresado e = controlador.buscarEgresadoTipo(tipoDocumento, numeroDocumento);
	        	if(e == null ){
	                JOptionPane.showMessageDialog(null, "No se ha encontrado ningun egresado con el numero de documento "+numeroDocumento, "Administrador de Egresados", JOptionPane.WARNING_MESSAGE); 
	        	}else{
	        		e.setApellido(apellido);
	        		e.setCelular(celular);
	        		e.setCorreo(correo);
	        		e.setNombre(nombre);
	        		e.setTelefono(telefono);
	        		e.setCelular(celular);
	        		
	        		InformacionAcademica i = controlador.buscarInfoAcademica(e.getId());
	        		if(i != null){
		        		i.setFacultad(facultad);
		        		i.setFechaGrado(fechaGrado);
		        		i.setNivelAcademico(nivelAcademico);
		        		i.setNumeroDiploma(numeroDiploma);
		        		i.setPrograma(programa);
	        		}
	        		InformacionLaboral l = controlador.buscarInfoLaboral(e.getId());
	        		if(l != null){
	        			l.setCargo(cargo);
	        			l.setEmpresa(empresa);
	        			l.setFechaIngreso(fechaIngreso);
	        			l.setFechaSalida(fechaSalida);
	        			l.setSituacionActual(situacionActual);
	        		}
	        		limpiarCampos();
	            	JOptionPane.showMessageDialog(null, "Se ha Actualizado la informacion del Egresado "+e.getNombre()+" "+e.getApellido(), "Administrador de Egresados", JOptionPane.INFORMATION_MESSAGE);
	        	}
        	}catch(Exception e){
	            JOptionPane.showMessageDialog(null, "Ha ocurrido un error.", "Administrador de Egresados", JOptionPane.ERROR_MESSAGE); 
        		e.printStackTrace();
        	}
    	}
    }

    private void jBEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBEliminarActionPerformed

    private void jTnombre1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTnombre1KeyTyped
        char c = evt.getKeyChar();
        if((c<'a' || c>'z') && (c<'A' || c>'Z') && ( c!=' ') && (c != evt.VK_BACK_SPACE)){
            evt.consume();
            JOptionPane.showMessageDialog(null, "Por favor, solo letras", "Informacion", JOptionPane.INFORMATION_MESSAGE);   
        }
    }//GEN-LAST:event_jTnombre1KeyTyped

    private void jTTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTTelefonoKeyTyped
        char c = evt.getKeyChar();
        if((c<'0' || c>'9') && (c != evt.VK_BACK_SPACE)){
            evt.consume();
            JOptionPane.showMessageDialog(null, "Por favor, solo numeros", "Informacion", JOptionPane.INFORMATION_MESSAGE); 
        }
    }//GEN-LAST:event_jTTelefonoKeyTyped

    private void jTCelularKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTCelularKeyTyped
        char c = evt.getKeyChar();
        if((c<'0' || c>'9') && (c != evt.VK_BACK_SPACE)){
            evt.consume();
            JOptionPane.showMessageDialog(null, "Por favor, solo numeros", "Informacion", JOptionPane.INFORMATION_MESSAGE);   
        }
    }//GEN-LAST:event_jTCelularKeyTyped

    private void jTNumeroDocumentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTNumeroDocumentoKeyTyped
        char c = evt.getKeyChar();
        if((c<'0' || c>'9') && (c != evt.VK_BACK_SPACE)){
            evt.consume();
            JOptionPane.showMessageDialog(null, "Por favor, solo numeros", "Informacion", JOptionPane.INFORMATION_MESSAGE);   
        }
    }//GEN-LAST:event_jTNumeroDocumentoKeyTyped

    private void jTNDiplomaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTNDiplomaKeyTyped
        char c = evt.getKeyChar();
        if((c<'0' || c>'9') && (c != evt.VK_BACK_SPACE)){
            evt.consume();
            JOptionPane.showMessageDialog(null, "Por favor, solo numeros", "Informacion", JOptionPane.INFORMATION_MESSAGE);   
        }
    }//GEN-LAST:event_jTNDiplomaKeyTyped

    private void jTapellido1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTapellido1KeyTyped
        char c = evt.getKeyChar();
        if((c<'a' || c>'z') && (c<'A' || c>'Z') && ( c!=' ') && (c != evt.VK_BACK_SPACE)){
            evt.consume();
            JOptionPane.showMessageDialog(null, "Por favor, solo letras", "Informacion", JOptionPane.INFORMATION_MESSAGE);   
        }
    }//GEN-LAST:event_jTapellido1KeyTyped
    /**
     * Defino una lista para agregar las listas de interes del egresado
     * 
     */
	List<AreaInteres> misAreas = new ArrayList<AreaInteres>();
	
    private void jBAgregarInteresActionPerformed(java.awt.event.ActionEvent evt) {                                                 
    	if(jTableAreasConocimiento.getSelectedRow() != -1){
    		try{
	    		int pos = jTableAreasConocimiento.getSelectedRow();
	    		List<AreaInteres> areasInteres = controlador.listarAreaInteres();
	    		AreaInteres a = areasInteres.get(pos);
	    		boolean encontrada = false;
	    		for (AreaInteres ai : misAreas) {
					if(ai.getNombre().equalsIgnoreCase(a.getNombre())){
						encontrada = true;
					}
				}
	    		if(encontrada){
	                JOptionPane.showMessageDialog(null, "Esta area de interes ya esta entre tus areas de interes", "Informacion", JOptionPane.WARNING_MESSAGE);   
				}else{
					misAreas.add(a);
					misAreasDeInteres();
				}
    		}catch(Exception e){
    			e.printStackTrace();
    		}
    	}
    }
    /**
     * tabla con todas las areas de interes registradas en la bd
     */
    public void misAreasDeInteres(){
    		DefaultTableModel table = (DefaultTableModel) jTableAreasConocimiento1.getModel();
    		table.setRowCount(0);
    		if(misAreas != null){
    			jBEliminarInteres.setVisible(true);
				for (AreaInteres a : misAreas) {
					table.addRow(new Object[]{a.getNombre()});
				}
    		}else{
    			jBEliminarInteres.setVisible(false);
    		}
    }
    private void jBEliminarInteresActionPerformed(java.awt.event.ActionEvent evt) {                                                  
    	if(jTableAreasConocimiento1.getSelectedRow() != -1){
	    		int pos = jTableAreasConocimiento1.getSelectedRow();
	    		misAreas.remove(pos);
	    		misAreasDeInteres();
    	}
    }
    /**
     * Este evento nos permitira cargar los programas dependiendo de lo que se eliga en facultad
     */
    private void jCFacultadItemStateChanged(java.awt.event.ItemEvent evt) {                                            
      	 Facultad facultad = (Facultad) jCFacultad.getSelectedItem();
       	 if(facultad != null){
       		try {
       			cargarProgramas(facultad);
    		} catch (Exception e) {
    			e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Ups! ha ocurrido un error.", "Administrador", JOptionPane.ERROR_MESSAGE);   
    		}
       	 }
    }

    private void jBAnteriorActionPerformed(java.awt.event.ActionEvent evt) {
            jTabbedPane1.setEnabledAt(selec, false);
            selec = selec - 1;
            jTabbedPane1.setEnabledAt(selec, true);
            jTabbedPane1.setSelectedIndex(selec);
            jBSiguiente.setText("Siguiente");
            jBSiguiente.setToolTipText("Siguiente");
            jBSiguiente.setBackground(new Color(66,103,178));
    	if(selec == 0){
    		jBAnterior.setVisible(false);
    	}
    }
    /**
     * Cargamos todas las Facultades registradas que se encuentran  en la bd
     */
    public void cargarFacultades(){
    	try{
	    	jCFacultad.removeAllItems();
	    	List<Facultad> lista = controlador.listarFacultades();
	    	for (Facultad facultad : lista) {
	    		jCFacultad.addItem(facultad);
			}
		}catch(Exception e){
			e.printStackTrace();
		}
    }
    
    /**
     * Cargamos todas los Programas de una facultad que se encuentran registradas en la bd
     */
    public void cargarProgramas(Facultad facultad){
    	try{
	    	jCPrograma.removeAllItems();
	    	List<Programa> lista = controlador.listarProgramaFacultad(facultad);
	    	for (Programa programa : lista) {
	    		jCPrograma.addItem(programa);
			}
    	}catch(Exception e){
    		e.printStackTrace();
    	}
    }
    
    /**
     * Cargamos todas los Sectores Laboral que se encuentran en la bd
     */
    public void cargarEmpresas(){
    	try{
    		jCEmpresa.removeAllItems();
	    	List<Empresa> lista = controlador.listarEmpresas();
	    	for (Empresa sl : lista) {
	    		jCEmpresa.addItem(sl);
			}
    	}catch(Exception e){
    		e.printStackTrace();
    	}
    }
    /**
     * llenamos la tabla con todas las areas de conocimiento registradas
     * en la base de datos
     */
    public void cargarAreasConocimiento(){
    	try {
    		DefaultTableModel table = (DefaultTableModel) jTableAreasConocimiento.getModel();
    		table.setRowCount(0);
    		List<AreaInteres> areasInteres = controlador.listarAreaInteres();
    		if(areasInteres.size() > 0){
				for (AreaInteres a : areasInteres) {
					table.addRow(new Object[]{a.getNombre()});
				}
    		}
		} catch (Exception e) {
			e.printStackTrace();
		}
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAgregarInteres;
    private javax.swing.JButton jBAgregarPalabra;
    private javax.swing.JButton jBAnterior;
    private javax.swing.JButton jBBuscar;
    private javax.swing.JButton jBEditar;
    private javax.swing.JButton jBEliminar;
    private javax.swing.JButton jBEliminarInteres;
    private javax.swing.JButton jBHome1;
    private javax.swing.JButton jBSiguiente;
    private javax.swing.JButton jBcANCELAR;
    private javax.swing.JComboBox jCBDocumento1;
    private javax.swing.JComboBox jCEmpresa;
    private javax.swing.JComboBox jCFacultad;
    private javax.swing.JComboBox jCNivelAcad;
    private javax.swing.JComboBox jCPrograma;
    private javax.swing.JComboBox jCSituacionActual;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateFechaGrado;
    private com.toedter.calendar.JDateChooser jDateIngreso;
    private com.toedter.calendar.JDateChooser jDateSalida;
    private javax.swing.JLabel jLApellido1;
    private javax.swing.JLabel jLFacultad;
    private javax.swing.JLabel jLFacultad1;
    private javax.swing.JLabel jLFacultad2;
    private javax.swing.JLabel jLFecha;
    private javax.swing.JLabel jLNivel;
    private javax.swing.JLabel jLNumero;
    private javax.swing.JLabel jLPrograma;
    private javax.swing.JLabel jLTipoDocumento1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLcelular;
    private javax.swing.JLabel jLcorreo;
    private javax.swing.JLabel jLnombre3;
    private javax.swing.JLabel jLnombre4;
    private javax.swing.JLabel jLnombre5;
    private javax.swing.JLabel jLnombre6;
    private javax.swing.JLabel jLnumeroDocumento;
    private javax.swing.JLabel jLtelefono;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTCargo;
    private javax.swing.JTextField jTCelular;
    private javax.swing.JTextField jTCorreo;
    private javax.swing.JTextField jTNDiploma;
    private javax.swing.JTextField jTNumeroDocumento;
    private javax.swing.JTextField jTTelefono;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableAreasConocimiento;
    private javax.swing.JTable jTableAreasConocimiento1;
    private javax.swing.JTextField jTapellido1;
    private javax.swing.JTextField jTnombre1;
    // End of variables declaration//GEN-END:variables
}
