/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.eam.ingesoft.desarrollo.vista.gui;

import java.util.List;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

import co.edu.eam.desarrollo.proyectoFinal.gui.controladores.ControladorVentanaAreaInteres;
import co.edu.eam.desarrollo.proyectoFinal.gui.controladores.ControladorVentanaFacultad;
import co.edu.eam.desarrollo.proyectoFinal.gui.controladores.ControladorVentanaPrograma;
import co.edu.eam.desarrollo.proyectoFinal.logica.excepciones.ExcepcionNegocio;
import co.edu.eam.desarrolloSoftware.proyectoFinal.modelo.AreaInteres;
import co.edu.eam.desarrolloSoftware.proyectoFinal.modelo.Facultad;
import co.edu.eam.desarrolloSoftware.proyectoFinal.modelo.Programa;

/**
 *
 * @author Carlos Alfredo Martinez Villada
 */
public class Parametrica extends javax.swing.JFrame {

	private ControladorVentanaPrograma controladorVentanaProgra;
	private ControladorVentanaFacultad controladorVentanaFacul;
	private ControladorVentanaAreaInteres controladorVentanaAreaIn;

	/**
	 * Creates new form parametrica
	 */
	public Parametrica() {

		initComponents();
		this.setTitle("Informacion Parametrica");
		this.setLocationRelativeTo(null);
		this.setResizable(false);
		this.setIconImage(new ImageIcon(getClass().getResource("/imagenes/icono.png")).getImage());
		controladorVentanaProgra = new ControladorVentanaPrograma();
		controladorVentanaFacul = new ControladorVentanaFacultad();
		controladorVentanaAreaIn = new ControladorVentanaAreaInteres();
		listarFacultades();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel2 = new javax.swing.JPanel();
		jTabbedPane1 = new javax.swing.JTabbedPane();
		jPanel1 = new javax.swing.JPanel();
		jLnombrePrograma = new javax.swing.JLabel();
		jTNomPrograma = new javax.swing.JTextField();
		jLFacultad = new javax.swing.JLabel();
		jBCrearPrograma = new javax.swing.JButton();
		jBEditarPrograma = new javax.swing.JButton();
		jLabel1 = new javax.swing.JLabel();
		jTcodigoPrograma = new javax.swing.JTextField();
		jCFacultad = new javax.swing.JComboBox();
		jBbuscarPrograma = new javax.swing.JButton();
		jPanel3 = new javax.swing.JPanel();
		jTCodigoFacultad = new javax.swing.JTextField();
		jLnombre = new javax.swing.JLabel();
		jBCrearFacultad = new javax.swing.JButton();
		jBEditarFacultad = new javax.swing.JButton();
		jLnombre2 = new javax.swing.JLabel();
		jTNombreFacultad = new javax.swing.JTextField();
		jBbuscarFacul = new javax.swing.JButton();
		jPanel4 = new javax.swing.JPanel();
		jLnombre1 = new javax.swing.JLabel();
		jTNomAreaInteres = new javax.swing.JTextField();
		jBCrearAreaInteres = new javax.swing.JButton();
		jBEditarAreaInteres = new javax.swing.JButton();
		jLabel2 = new javax.swing.JLabel();
		jTCodigoAreaInteres = new javax.swing.JTextField();
		jBbuscarAreaInt = new javax.swing.JButton();
		jBAgregarPalabra = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jPanel2.setBackground(new java.awt.Color(242, 242, 249));

		jPanel1.setBackground(new java.awt.Color(255, 255, 255));

		jLnombrePrograma.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
		jLnombrePrograma.setForeground(new java.awt.Color(51, 51, 51));
		jLnombrePrograma.setText("Nombre:");

		jTNomPrograma.setBackground(new java.awt.Color(242, 242, 249));
		jTNomPrograma.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
		jTNomPrograma.setForeground(new java.awt.Color(43, 43, 74));
		jTNomPrograma.setToolTipText("");
		jTNomPrograma.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(232, 232, 240)));
		jTNomPrograma.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyTyped(java.awt.event.KeyEvent evt) {
				jTNomProgramaKeyTyped(evt);
			}
		});

		jLFacultad.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
		jLFacultad.setForeground(new java.awt.Color(51, 51, 51));
		jLFacultad.setText("Facultad:");

		jBCrearPrograma.setText("CREAR");
		jBCrearPrograma.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jBCrearProgramaActionPerformed(evt);
			}
		});

		jBEditarPrograma.setText("EDITAR");
		jBEditarPrograma.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jBEditarProgramaActionPerformed(evt);
			}
		});

		jLabel1.setText("Codigo:");

		jTcodigoPrograma.setBackground(new java.awt.Color(242, 242, 249));
		jTcodigoPrograma.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
		jTcodigoPrograma.setForeground(new java.awt.Color(43, 43, 74));
		jTcodigoPrograma.setToolTipText("");
		jTcodigoPrograma.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(232, 232, 240)));
		jTcodigoPrograma.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyTyped(java.awt.event.KeyEvent evt) {
				jTcodigoProgramaKeyTyped(evt);
			}
		});

		jBbuscarPrograma.setText("BUSCAR");
		jBbuscarPrograma.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jBbuscarProgramaActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addGap(120, 120, 120)
						.addComponent(jBCrearPrograma, javax.swing.GroupLayout.PREFERRED_SIZE, 91,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18)
						.addComponent(jBbuscarPrograma, javax.swing.GroupLayout.PREFERRED_SIZE, 86,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18)
						.addComponent(jBEditarPrograma,
								javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(129, Short.MAX_VALUE))
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addComponent(jLabel1).addComponent(jLnombrePrograma).addComponent(jLFacultad))
						.addGap(98, 98, 98)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
								.addComponent(jTNomPrograma, javax.swing.GroupLayout.Alignment.LEADING,
										javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
								.addComponent(jTcodigoPrograma, javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jCFacultad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addGap(56, 56, 56)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addGap(62, 62, 62)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel1).addComponent(jTcodigoPrograma,
										javax.swing.GroupLayout.PREFERRED_SIZE, 30,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jTNomPrograma, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLnombrePrograma, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(jLFacultad, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGroup(
										jPanel1Layout.createSequentialGroup().addComponent(jCFacultad).addGap(4, 4, 4)))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jBCrearPrograma, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jBEditarPrograma, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jBbuscarPrograma, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(59, 59, 59)));

		jTabbedPane1.addTab("Gestion de Programa", jPanel1);

		jPanel3.setBackground(new java.awt.Color(255, 255, 255));

		jTCodigoFacultad.setBackground(new java.awt.Color(242, 242, 249));
		jTCodigoFacultad.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
		jTCodigoFacultad.setForeground(new java.awt.Color(43, 43, 74));
		jTCodigoFacultad.setToolTipText("");
		jTCodigoFacultad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(232, 232, 240)));
		jTCodigoFacultad.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyTyped(java.awt.event.KeyEvent evt) {
				jTCodigoFacultadKeyTyped(evt);
			}
		});

		jLnombre.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
		jLnombre.setForeground(new java.awt.Color(51, 51, 51));
		jLnombre.setText("Codigo:");

		jBCrearFacultad.setText("CREAR");
		jBCrearFacultad.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jBCrearFacultadActionPerformed(evt);
			}
		});

		jBEditarFacultad.setText("EDITAR");
		jBEditarFacultad.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jBEditarFacultadActionPerformed(evt);
			}
		});

		jLnombre2.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
		jLnombre2.setForeground(new java.awt.Color(51, 51, 51));
		jLnombre2.setText("Nombre");

		jTNombreFacultad.setBackground(new java.awt.Color(242, 242, 249));
		jTNombreFacultad.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
		jTNombreFacultad.setForeground(new java.awt.Color(43, 43, 74));
		jTNombreFacultad.setToolTipText("");
		jTNombreFacultad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(232, 232, 240)));
		jTNombreFacultad.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyTyped(java.awt.event.KeyEvent evt) {
				jTNombreFacultadKeyTyped(evt);
			}
		});

		jBbuscarFacul.setText("BUSCAR");
		jBbuscarFacul.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jBbuscarFaculActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout.setHorizontalGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel3Layout.createSequentialGroup().addGap(117, 117, 117)
						.addComponent(jBCrearFacultad, javax.swing.GroupLayout.PREFERRED_SIZE, 91,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(jBbuscarFacul, javax.swing.GroupLayout.PREFERRED_SIZE, 89,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18)
						.addComponent(jBEditarFacultad, javax.swing.GroupLayout.PREFERRED_SIZE, 99,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
				.addGroup(jPanel3Layout.createSequentialGroup().addGap(75, 75, 75)
						.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addComponent(jLnombre2).addComponent(jLnombre))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
						.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jTCodigoFacultad, javax.swing.GroupLayout.PREFERRED_SIZE, 277,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jTNombreFacultad, javax.swing.GroupLayout.PREFERRED_SIZE, 277,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(61, 61, 61)));
		jPanel3Layout.setVerticalGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel3Layout.createSequentialGroup().addGap(70, 70, 70)
						.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jTCodigoFacultad, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel3Layout.createSequentialGroup().addGap(31, 31, 31).addComponent(
										jLnombre2, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
										javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(jPanel3Layout.createSequentialGroup().addGap(42, 42, 42).addComponent(
										jTNombreFacultad, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
										javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
						.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jBCrearFacultad, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jBEditarFacultad, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jBbuscarFacul, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(61, 61, 61)));

		jTabbedPane1.addTab("Gestion Facultad", jPanel3);

		jPanel4.setBackground(new java.awt.Color(255, 255, 255));

		jLnombre1.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
		jLnombre1.setForeground(new java.awt.Color(51, 51, 51));
		jLnombre1.setText("Nombre");

		jTNomAreaInteres.setBackground(new java.awt.Color(242, 242, 249));
		jTNomAreaInteres.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
		jTNomAreaInteres.setForeground(new java.awt.Color(43, 43, 74));
		jTNomAreaInteres.setToolTipText("");
		jTNomAreaInteres.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(232, 232, 240)));
		jTNomAreaInteres.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyTyped(java.awt.event.KeyEvent evt) {
				jTNomAreaInteresKeyTyped(evt);
			}
		});

		jBCrearAreaInteres.setText("CREAR");
		jBCrearAreaInteres.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jBCrearAreaInteresActionPerformed(evt);
			}
		});

		jBEditarAreaInteres.setText("EDITAR");
		jBEditarAreaInteres.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jBEditarAreaInteresActionPerformed(evt);
			}
		});

		jLabel2.setText("CodigoArea");

		jTCodigoAreaInteres.setBackground(new java.awt.Color(242, 242, 249));
		jTCodigoAreaInteres.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
		jTCodigoAreaInteres.setForeground(new java.awt.Color(43, 43, 74));
		jTCodigoAreaInteres.setToolTipText("");
		jTCodigoAreaInteres.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(232, 232, 240)));
		jTCodigoAreaInteres.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyTyped(java.awt.event.KeyEvent evt) {
				jTCodigoAreaInteresKeyTyped(evt);
			}
		});

		jBbuscarAreaInt.setText("BUSCAR");
		jBbuscarAreaInt.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jBbuscarAreaIntActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
		jPanel4.setLayout(jPanel4Layout);
		jPanel4Layout.setHorizontalGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel4Layout.createSequentialGroup().addGap(116, 116, 116)
						.addComponent(jBCrearAreaInteres, javax.swing.GroupLayout.PREFERRED_SIZE, 91,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(16, 16, 16)
						.addComponent(jBbuscarAreaInt, javax.swing.GroupLayout.PREFERRED_SIZE, 89,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(jBEditarAreaInteres, javax.swing.GroupLayout.PREFERRED_SIZE, 99,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
				.addGroup(jPanel4Layout.createSequentialGroup().addGap(62, 62, 62)
						.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addComponent(jLabel2).addComponent(jLnombre1))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
						.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jTNomAreaInteres, javax.swing.GroupLayout.PREFERRED_SIZE, 277,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jTCodigoAreaInteres, javax.swing.GroupLayout.PREFERRED_SIZE, 277,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(132, 132, 132)));
		jPanel4Layout.setVerticalGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel4Layout.createSequentialGroup().addContainerGap(59, Short.MAX_VALUE)
						.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel2).addComponent(jTCodigoAreaInteres,
										javax.swing.GroupLayout.PREFERRED_SIZE, 30,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(33, 33, 33)
						.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jTNomAreaInteres, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLnombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(89, 89, 89)
						.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jBCrearAreaInteres, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jBEditarAreaInteres, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jBbuscarAreaInt, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(61, 61, 61)));

		jTabbedPane1.addTab("Gestion Area Interes", jPanel4);

		jBAgregarPalabra.setBackground(new java.awt.Color(66, 183, 42));
		jBAgregarPalabra.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
		jBAgregarPalabra.setForeground(new java.awt.Color(255, 255, 255));
		jBAgregarPalabra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Inicio.png"))); // NOI18N
		jBAgregarPalabra.setToolTipText("Ir al inicio");
		jBAgregarPalabra.setBorder(null);
		jBAgregarPalabra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		jBAgregarPalabra.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jBAgregarPalabraActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(
				jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jTabbedPane1)
						.addGroup(jPanel2Layout.createSequentialGroup().addGap(23, 23, 23)
								.addComponent(jBAgregarPalabra, javax.swing.GroupLayout.PREFERRED_SIZE, 52,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup()
						.addComponent(jTabbedPane1).addGap(23, 23, 23).addComponent(jBAgregarPalabra,
								javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(23, 23, 23)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jBbuscarProgramaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jBbuscarProgramaActionPerformed
		try {
			if (jTcodigoPrograma.getText().isEmpty()) {
				JOptionPane.showMessageDialog(null, "Porfavor ingrese el codigo");
			} else {
				int codigo = Integer.parseInt(jTcodigoPrograma.getText());
				Programa pr = controladorVentanaProgra.buscarPrograma(codigo);
				if (pr != null) {
					jTcodigoPrograma.setText(pr.getId() + "");
					jTNomPrograma.setText(pr.getNombre());
					jCFacultad.setSelectedItem(pr.getFacultad());

				} else {
					JOptionPane.showMessageDialog(null,
							"el Programa con el codigo: " + codigo + " no se encuentra registrado");
				}
			}
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

	}

	private void jBbuscarFaculActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jBbuscarFaculActionPerformed

		try {
			if (jTCodigoFacultad.getText().isEmpty()) {
				JOptionPane.showMessageDialog(null, "Porfavor ingrese el codigo");
			} else {
				int codigo = Integer.parseInt(jTCodigoFacultad.getText());
				Facultad f = controladorVentanaFacul.buscarFacultad(codigo);
				if (f != null) {
					jTCodigoFacultad.setText(f.getId() + "");
					jTNombreFacultad.setText(f.getNombre());

				} else {
					JOptionPane.showMessageDialog(null,
							"La Facultad con el codigo: " + codigo + " no se encuentra registrado");
				}
			}
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

	}

	private void jBbuscarAreaIntActionPerformed(java.awt.event.ActionEvent evt) {
		try {
			if (jTCodigoAreaInteres.getText().isEmpty()) {
				JOptionPane.showMessageDialog(null, "Porfavor ingrese el codigo");
			} else {
				int codigo = Integer.parseInt(jTCodigoAreaInteres.getText());
				AreaInteres area = controladorVentanaAreaIn.buscarArea(codigo);
				if (area != null) {
					jTCodigoAreaInteres.setText(area.getId() + "");
					jTNomAreaInteres.setText(area.getNombre());

				} else {
					JOptionPane.showMessageDialog(null,
							"El area con el codigo: " + codigo + "no se encuentra registrada");
				}
			}
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

	}

	private void jBAgregarPalabraActionPerformed(java.awt.event.ActionEvent evt) {
		VentanaPrincipal vp = new VentanaPrincipal();
		vp.setVisible(true);
		this.setVisible(false);
	}// GEN-LAST:event_jBAgregarPalabraActionPerformed

	private void jBCrearProgramaActionPerformed(java.awt.event.ActionEvent evt) {

		try {
			if (jTcodigoPrograma.getText().isEmpty() || jTNomPrograma.getText().isEmpty()
					|| jCFacultad.getSelectedIndex() == 0) {
				JOptionPane.showMessageDialog(null, "Porfavor ingrese todos los datos");
			} else {
				int codigo = Integer.parseInt(jTcodigoPrograma.getText());
				String nombre = jTNomPrograma.getText();
				Facultad fac = (Facultad) jCFacultad.getSelectedItem();
				Programa pro = new Programa(codigo, fac, nombre);
				controladorVentanaProgra.crearPrograma(pro);
				JOptionPane.showMessageDialog(null, "se ha registrado el programa");
				LimpiarCamposPrograma();
			}
		} catch (ExcepcionNegocio ex) {
			JOptionPane.showMessageDialog(null, ex.getMessage());
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	private void jBEditarProgramaActionPerformed(java.awt.event.ActionEvent evt) {

		if (jTcodigoPrograma.getText().isEmpty()) {
			JOptionPane.showMessageDialog(null, "Debe buscar el programa primero");
		} else {
			try {
				int codigo = Integer.parseInt(jTcodigoPrograma.getText());
				String nombre = jTNomPrograma.getText();
				Facultad fac = (Facultad) jCFacultad.getSelectedItem();
				Programa pro = new Programa(codigo, fac, nombre);
				controladorVentanaProgra.editarPrograma(pro);
				JOptionPane.showMessageDialog(null, "se edito correctamente");

			} catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}

		}

	}

	private void jBCrearFacultadActionPerformed(java.awt.event.ActionEvent evt) {
		try {
			if (jTCodigoFacultad.getText().isEmpty() || jTNombreFacultad.getText().isEmpty()) {
				JOptionPane.showMessageDialog(null, "Porfavor ingrese todos los datos");
			} else {
				int codigo = Integer.parseInt(jTCodigoFacultad.getText());
				String nombre = jTNombreFacultad.getText();
				Facultad fac = new Facultad(codigo, nombre);
				controladorVentanaFacul.crearFacultad(fac);
				JOptionPane.showMessageDialog(null, "se ha registrado la facultad");
				listarFacultades();
				LimpiarCamposFacultas();
			}
		} catch (ExcepcionNegocio ex) {
			JOptionPane.showMessageDialog(null, ex.getMessage());
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

	}

	private void jBEditarFacultadActionPerformed(java.awt.event.ActionEvent evt) {
		if (jTCodigoFacultad.getText().isEmpty()) {
			JOptionPane.showMessageDialog(null, "Debe buscar la facultad primero");
		} else {
			try {
				int codigo = Integer.parseInt(jTCodigoFacultad.getText());
				String nombre = jTNombreFacultad.getText();
				Facultad fac = new Facultad(codigo, nombre);
				controladorVentanaFacul.editarFacultad(fac);
				JOptionPane.showMessageDialog(null, "se edito correctamente");

			} catch (ExcepcionNegocio ex) {
				JOptionPane.showMessageDialog(null, ex.getMessage());
			} catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}

	}

	private void jBCrearAreaInteresActionPerformed(java.awt.event.ActionEvent evt) {
		try {
			if (jTCodigoAreaInteres.getText().isEmpty() || jTNomAreaInteres.getText().isEmpty()) {
				JOptionPane.showMessageDialog(null, "por favor ingrese todos los datos");
			} else {
				int codigo = Integer.parseInt(jTCodigoAreaInteres.getText());
				String nom = jTNomAreaInteres.getText();
				AreaInteres area = new AreaInteres(codigo, nom);
				controladorVentanaAreaIn.crearAreaInt(area);
				JOptionPane.showMessageDialog(null, "se ha registrado el Area correctamente");
				 LimpiarCamposAreaInt();
			}
		} catch (ExcepcionNegocio ex) {
			JOptionPane.showMessageDialog(null, ex.getMessage());
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

	}

	private void jBEditarAreaInteresActionPerformed(java.awt.event.ActionEvent evt) {
		try {
			if (jTCodigoAreaInteres.getText().isEmpty()) {
				JOptionPane.showMessageDialog(null, "Debe buscar el area de interes primero");
			} else {
				int codigo = Integer.parseInt(jTCodigoAreaInteres.getText());
				String nom = jTNomAreaInteres.getText();
				AreaInteres area = new AreaInteres(codigo, nom);
				controladorVentanaAreaIn.editarArea(area);
				JOptionPane.showMessageDialog(null, "se edito correctamente");
			}
		} catch (Exception e) {
			e.printStackTrace();
		}

	}

	private void jTNomProgramaKeyTyped(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_jTNomProgramaKeyTyped
		char c = evt.getKeyChar();
		if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z') && (c != ' ')) {
			evt.consume();
			JOptionPane.showMessageDialog(null, "Por favor, solo letras", "Informacion",
					JOptionPane.INFORMATION_MESSAGE);
		}
	}// GEN-LAST:event_jTNomProgramaKeyTyped

	private void jTCodigoFacultadKeyTyped(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_jTCodigoFacultadKeyTyped
		// int c = evt.getKeyCode();
		// if ((c < '1' || c > '')) {
		// evt.consume();
		// JOptionPane.showMessageDialog(null, "Por favor, solo numeros",
		// "Informacion",
		// JOptionPane.INFORMATION_MESSAGE);
		// }
	}// GEN-LAST:event_jTCodigoFacultadKeyTyped

	private void jTNomAreaInteresKeyTyped(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_jTNomAreaInteresKeyTyped
		char c = evt.getKeyChar();
		if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z') && (c != ' ')) {
			evt.consume();
			JOptionPane.showMessageDialog(null, "Por favor, solo letras", "Informacion",
					JOptionPane.INFORMATION_MESSAGE);
		}
	}// GEN-LAST:event_jTNomAreaInteresKeyTyped

	private void jTcodigoProgramaKeyTyped(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_jTcodigoProgramaKeyTyped
		// TODO add your handling code here:
	}// GEN-LAST:event_jTcodigoProgramaKeyTyped

	private void jTNombreFacultadKeyTyped(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_jTNombreFacultadKeyTyped
		char c = evt.getKeyChar();
		if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z') && (c != ' ')) {
			evt.consume();
			JOptionPane.showMessageDialog(null, "Por favor, solo letras", "Informacion",
					JOptionPane.INFORMATION_MESSAGE);
		}
	}// GEN-LAST:event_jTNombreFacultadKeyTyped

	private void jTCodigoAreaInteresKeyTyped(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_jTCodigoAreaInteresKeyTyped
		// TODO add your handling code here:
	}// GEN-LAST:event_jTCodigoAreaInteresKeyTyped

	public void listarFacultades() {
		try {
			jCFacultad.removeAllItems();
			jCFacultad.addItem("Seleccione una opción");
			List<Facultad> lista = controladorVentanaFacul.listarFacultad();
			for (int i = 0; i < lista.size(); i++) {

				jCFacultad.addItem(lista.get(i));

			}
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

	}

	public void LimpiarCamposPrograma() {
		jTcodigoPrograma.setText(null);
		jTNomPrograma.setText(null);
		jCFacultad.setSelectedIndex(0);
	}
	
	public void LimpiarCamposFacultas(){
		jTCodigoFacultad.setText(null);
		jTNombreFacultad.setText(null);
	}
	public void LimpiarCamposAreaInt(){
		jTCodigoAreaInteres.setText(null);
		jTNomAreaInteres.setText(null);
	}
	

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jBAgregarPalabra;
	private javax.swing.JButton jBCrearAreaInteres;
	private javax.swing.JButton jBCrearFacultad;
	private javax.swing.JButton jBCrearPrograma;
	private javax.swing.JButton jBEditarAreaInteres;
	private javax.swing.JButton jBEditarFacultad;
	private javax.swing.JButton jBEditarPrograma;
	private javax.swing.JButton jBbuscarAreaInt;
	private javax.swing.JButton jBbuscarFacul;
	private javax.swing.JButton jBbuscarPrograma;
	private javax.swing.JComboBox jCFacultad;
	private javax.swing.JLabel jLFacultad;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLnombre;
	private javax.swing.JLabel jLnombre1;
	private javax.swing.JLabel jLnombre2;
	private javax.swing.JLabel jLnombrePrograma;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JTextField jTCodigoAreaInteres;
	private javax.swing.JTextField jTCodigoFacultad;
	private javax.swing.JTextField jTNomAreaInteres;
	private javax.swing.JTextField jTNomPrograma;
	private javax.swing.JTextField jTNombreFacultad;
	private javax.swing.JTabbedPane jTabbedPane1;
	private javax.swing.JTextField jTcodigoPrograma;
	// End of variables declaration//GEN-END:variables
}
