/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.eam.ingesoft.desarrollo.vista.gui;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JPanel;
import javax.swing.UIManager;
/**
 *
 * @author carlos alfredo martinez villada
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() { 
        initComponents();
//        try{
//          UIManager.setLookAndFeel(new SyntheticaPlainLookAndFeel());
//        }catch (Exception e) {
//          e.printStackTrace();
//        }
        
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setIconImage(new ImageIcon(getClass().getResource("/imagenes/icono.png")).getImage());
        ((JPanel)getContentPane()).setOpaque(false);
        ImageIcon fondo = new ImageIcon(this.getClass().getResource("/imagenes/fondo.png"));
        JLabel labe = new JLabel();
        labe.setIcon(fondo);
        getLayeredPane().add(labe, JLayeredPane.FRAME_CONTENT_LAYER);
        labe.setBounds(0, 0, fondo.getIconWidth(), fondo.getIconHeight()); 
        jPanelContenido.setBackground(new Color(0, 0, 0, 50));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelContenido = new javax.swing.JPanel();
        jBEgresados = new javax.swing.JButton();
        jBEmpresas = new javax.swing.JButton();
        jBReportes = new javax.swing.JButton();
        jBParametrica = new javax.swing.JButton();
        jLMsj = new javax.swing.JLabel();
        jLnamePrograma = new javax.swing.JLabel();
        jLMsj1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jBEgresados.setBackground(new java.awt.Color(115, 230, 121));
        jBEgresados.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jBEgresados.setForeground(new java.awt.Color(255, 255, 255));
        jBEgresados.setText("Egresados");
        jBEgresados.setBorder(null);
        jBEgresados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBEgresados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEgresadosActionPerformed(evt);
            }
        });

        jBEmpresas.setBackground(new java.awt.Color(115, 230, 121));
        jBEmpresas.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jBEmpresas.setForeground(new java.awt.Color(255, 255, 255));
        jBEmpresas.setText("Empresas");
        jBEmpresas.setBorder(null);
        jBEmpresas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBEmpresas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEmpresasActionPerformed(evt);
            }
        });

        jBReportes.setBackground(new java.awt.Color(115, 230, 121));
        jBReportes.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jBReportes.setForeground(new java.awt.Color(255, 255, 255));
        jBReportes.setText("Reportes");
        jBReportes.setBorder(null);
        jBReportes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBReportesActionPerformed(evt);
            }
        });

        jBParametrica.setBackground(new java.awt.Color(115, 230, 121));
        jBParametrica.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jBParametrica.setForeground(new java.awt.Color(255, 255, 255));
        jBParametrica.setText(" Paramétrica");
        jBParametrica.setBorder(null);
        jBParametrica.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBParametrica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBParametricaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelContenidoLayout = new javax.swing.GroupLayout(jPanelContenido);
        jPanelContenido.setLayout(jPanelContenidoLayout);
        jPanelContenidoLayout.setHorizontalGroup(
            jPanelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContenidoLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBParametrica, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBEgresados, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBEmpresas, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanelContenidoLayout.setVerticalGroup(
            jPanelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContenidoLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(jPanelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBEgresados, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBEmpresas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBParametrica, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        jLMsj.setFont(new java.awt.Font("CordiaUPC", 0, 36)); // NOI18N
        jLMsj.setForeground(new java.awt.Color(193, 218, 253));
        jLMsj.setText("Selecciona la Actividad");

        jLnamePrograma.setFont(new java.awt.Font("CordiaUPC", 1, 36)); // NOI18N
        jLnamePrograma.setForeground(new java.awt.Color(255, 255, 255));
        jLnamePrograma.setText("EmpleoEAM");

        jLMsj1.setFont(new java.awt.Font("CordiaUPC", 0, 18)); // NOI18N
        jLMsj1.setForeground(new java.awt.Color(193, 218, 253));
        jLMsj1.setText("Carlos Martinez &  Roman © 2016 ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 66, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jPanelContenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLnamePrograma)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLMsj)
                                .addGap(86, 86, 86))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLMsj1)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLMsj)
                    .addComponent(jLnamePrograma))
                .addGap(32, 32, 32)
                .addComponent(jPanelContenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(jLMsj1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBEgresadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEgresadosActionPerformed
        Egresados e = new Egresados();
        e.setVisible(true); 
        this.setVisible(false);
    }//GEN-LAST:event_jBEgresadosActionPerformed

    private void jBEmpresasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEmpresasActionPerformed
        Empresas e = new Empresas();
        e.setVisible(true); 
        this.setVisible(false);
    }//GEN-LAST:event_jBEmpresasActionPerformed

    private void jBReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBReportesActionPerformed
        ReportesEstadisticas re = new ReportesEstadisticas();
        re.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jBReportesActionPerformed

    private void jBParametricaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBParametricaActionPerformed
        Parametrica p = new Parametrica();
        p.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jBParametricaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBEgresados;
    private javax.swing.JButton jBEmpresas;
    private javax.swing.JButton jBParametrica;
    private javax.swing.JButton jBReportes;
    private javax.swing.JLabel jLMsj;
    private javax.swing.JLabel jLMsj1;
    private javax.swing.JLabel jLnamePrograma;
    private javax.swing.JPanel jPanelContenido;
    // End of variables declaration//GEN-END:variables
}
